'''
Author: Walker Kroubalkian
Implementation of Affine Cipher Decryption without Key in Python 2.7
'''

import time

cipherText = "LREKMEPQOCPCBOYGYWPPEHFIWPFZYQGDZERGYPWFYWECYOJEQCMYEGFGYPWFCYMJYFGFMFGWPQGDZERGPGFFZEYCIEDBCGPFEHFBEFFERQCPJEEPQRODFEXFWCPOWPEWLYETERCBXGLLEREPFQGDZERFEHFBEFFERYXEDEPXGPSWPGFYDWYGFGWPGPFZEIEYYCSE"

def modInverse(r,m):
    for i in range(1,m):
        if(r*i%m==1):
            return i
    return -1

def affineDecrypt(c,mu,sh):
    c = c.lower()
    s = ""
    v = ord("a")
    w = modInverse(mu, 26)
    for x in c:
        s+=chr(v+((ord(x)-v-sh)*w)%26)
    return s

def gcd(a,b):
    if(a<0 or b<0):
        return gcd(abs(a),abs(b))
    if(min(a,b)==0):
        return max(a,b)
    if(a>b):
        return gcd(b,a%b)
    return gcd(a,b%a)

def affineBruteForce(c):
    for mu in range(1,26):
        if(gcd(mu,26)==1):
            for sh in range(26):
                print "Mu: " + str(mu) + ", Sh: " + str(sh) + ", M: " + affineDecrypt(c, mu, sh)
    exit

start = time.time()
affineBruteForce(cipherText)
print ("--- %s seconds ---" % (time.time()-start))

'''
Prints

Mu: 1, Sh: 0, M: lrekmepqocpcboygywppehfiwpfzyqgdzergypwfywecyojeqcmyegfgypwfcymjyfgfmfgwpqgdzergpgffzeyciedbcgpfehfbefferqcpjeepqrodfexfwcpowpewlyetercbxgllerepfqgdzerfehfbefferyxedepxgpswpgfydwygfgwpgpfzeieyycse
Mu: 1, Sh: 1, M: kqdjldopnbobanxfxvoodgehvoeyxpfcydqfxovexvdbxnidpblxdfefxovebxlixefelefvopfcydqfofeeydxbhdcabfoedgeadeedqpboiddopqncedwevbonvodvkxdsdqbawfkkdqdoepfcydqedgeadeedqxwdcdowforvofexcvxfefvofoeydhdxxbrd
Mu: 1, Sh: 2, M: jpcikcnomanazmwewunncfdgundxwoebxcpewnudwucawmhcoakwcedewnudawkhwdedkdeunoebxcpeneddxcwagcbzaendcfdzcddcpoanhccnopmbdcvduanmuncujwcrcpazvejjcpcndoebxcpdcfdzcddcpwvcbcnvenqunedwbuwedeunendxcgcwwaqc
Mu: 1, Sh: 3, M: iobhjbmnlzmzylvdvtmmbecftmcwvndawbodvmtcvtbzvlgbnzjvbdcdvmtczvjgvcdcjcdtmndawbodmdccwbvzfbayzdmcbecybccbonzmgbbmnolacbuctzmltmbtivbqbozyudiibobmcndawbocbecybccbovubabmudmptmdcvatvdcdtmdmcwbfbvvzpb
Mu: 1, Sh: 4, M: hnagialmkylyxkucuslladbeslbvumczvanculsbusayukfamyiuacbculsbyuifubcbibcslmczvanclcbbvauyeazxyclbadbxabbanmylfaalmnkzbatbsylkslashuapanyxtchhanalbmczvanbadbxabbanutazaltcloslcbuzsucbcslclbvaeauuyoa
Mu: 1, Sh: 5, M: gmzfhzkljxkxwjtbtrkkzcadrkautlbyuzmbtkratrzxtjezlxhtzbabtkraxthetabahabrklbyuzmbkbaauztxdzywxbkazcawzaazmlxkezzklmjyazsarxkjrkzrgtzozmxwsbggzmzkalbyuzmazcawzaazmtszyzksbknrkbatyrtbabrkbkauzdzttxnz
Mu: 1, Sh: 6, M: flyegyjkiwjwvisasqjjybzcqjztskaxtylasjqzsqywsidykwgsyazasjqzwsgdszazgzaqjkaxtylajazztyswcyxvwajzybzvyzzylkwjdyyjklixzyrzqwjiqjyqfsynylwvraffylyjzkaxtylzybzvyzzylsryxyjrajmqjazsxqsazaqjajztycysswmy
Mu: 1, Sh: 7, M: ekxdfxijhvivuhrzrpiixaybpiysrjzwsxkzripyrpxvrhcxjvfrxzyzripyvrfcryzyfyzpijzwsxkzizyysxrvbxwuvziyxayuxyyxkjvicxxijkhwyxqypvihpixperxmxkvuqzeexkxiyjzwsxkyxayuxyyxkrqxwxiqzilpizyrwprzyzpiziysxbxrrvlx
Mu: 1, Sh: 8, M: djwcewhiguhutgqyqohhwzxaohxrqiyvrwjyqhoxqowuqgbwiueqwyxyqhoxuqebqxyxexyohiyvrwjyhyxxrwquawvtuyhxwzxtwxxwjiuhbwwhijgvxwpxouhgohwodqwlwjutpyddwjwhxiyvrwjxwzxtwxxwjqpwvwhpyhkohyxqvoqyxyohyhxrwawqqukw
Mu: 1, Sh: 9, M: civbdvghftgtsfpxpnggvywzngwqphxuqvixpgnwpnvtpfavhtdpvxwxpgnwtpdapwxwdwxnghxuqvixgxwwqvptzvustxgwvywsvwwvihtgavvghifuwvowntgfngvncpvkvitsoxccvivgwhxuqviwvywsvwwvipovuvgoxgjngxwpunpxwxngxgwqvzvpptjv
Mu: 1, Sh: 10, M: bhuacufgesfsreowomffuxvymfvpogwtpuhwofmvomusoezugscouwvwofmvsoczovwvcvwmfgwtpuhwfwvvpuosyutrswfvuxvruvvuhgsfzuufghetvunvmsfemfumboujuhsrnwbbuhufvgwtpuhvuxvruvvuhonutufnwfimfwvotmowvwmfwfvpuyuoosiu
Mu: 1, Sh: 11, M: agtzbtefdrerqdnvnleetwuxleuonfvsotgvnelunltrndytfrbntvuvnelurnbynuvubuvlefvsotgvevuuotnrxtsqrveutwuqtuutgfreyttefgdsutmulredletlantitgrqmvaatgteufvsotgutwuqtuutgnmtstemvehlevunslnvuvleveuotxtnnrht
Mu: 1, Sh: 12, M: zfsyasdecqdqpcmumkddsvtwkdtnmeurnsfumdktmksqmcxseqamsutumdktqmaxmtutatukdeurnsfuduttnsmqwsrpqudtsvtpsttsfeqdxssdefcrtsltkqdckdskzmshsfqpluzzsfsdteurnsftsvtpsttsfmlsrsdludgkdutmrkmutukdudtnswsmmqgs
Mu: 1, Sh: 13, M: yerxzrcdbpcpobltljccrusvjcsmldtqmretlcjsljrplbwrdpzlrtstlcjsplzwlstszstjcdtqmretctssmrlpvrqoptcsrusorssredpcwrrcdebqsrksjpcbjcrjylrgrepoktyyrercsdtqmresrusorssrelkrqrcktcfjctslqjltstjctcsmrvrllpfr
Mu: 1, Sh: 14, M: xdqwyqbcaobonakskibbqtruibrlkcsplqdskbirkiqokavqcoykqsrskbirokyvkrsryrsibcsplqdsbsrrlqkouqpnosbrqtrnqrrqdcobvqqbcdaprqjriobaibqixkqfqdonjsxxqdqbrcsplqdrqtrnqrrqdkjqpqbjsbeibsrkpiksrsibsbrlquqkkoeq
Mu: 1, Sh: 15, M: wcpvxpabznanmzjrjhaapsqthaqkjbrokpcrjahqjhpnjzupbnxjprqrjahqnjxujqrqxqrhabrokpcrarqqkpjntpomnraqpsqmpqqpcbnauppabczoqpiqhnazhaphwjpepcnmirwwpcpaqbrokpcqpsqmpqqpcjipopairadharqjohjrqrharaqkptpjjndp
Mu: 1, Sh: 16, M: vbouwozaymzmlyiqigzzorpsgzpjiaqnjobqizgpigomiytoamwioqpqizgpmiwtipqpwpqgzaqnjobqzqppjoimsonlmqzporploppobamztoozabynpohpgmzygzogviodobmlhqvvobozpaqnjobporploppobihonozhqzcgzqpingiqpqgzqzpjosoiimco
Mu: 1, Sh: 17, M: uantvnyzxlylkxhphfyynqorfyoihzpminaphyfohfnlhxsnzlvhnpophyfolhvshopovopfyzpminapypooinhlrnmklpyonqoknoonazlysnnyzaxmongoflyxfynfuhncnalkgpuunanyozpminaonqoknoonahgnmnygpybfypohmfhpopfypyoinrnhhlbn
Mu: 1, Sh: 18, M: tzmsumxywkxkjwgogexxmpnqexnhgyolhmzogxengemkgwrmykugmonogxenkgurgnonunoexyolhmzoxonnhmgkqmljkoxnmpnjmnnmzykxrmmxyzwlnmfnekxwexmetgmbmzkjfottmzmxnyolhmznmpnjmnnmzgfmlmxfoxaexonglegonoexoxnhmqmggkam
Mu: 1, Sh: 19, M: sylrtlwxvjwjivfnfdwwlompdwmgfxnkglynfwdmfdljfvqlxjtflnmnfwdmjftqfmnmtmndwxnkglynwnmmglfjplkijnwmlomilmmlyxjwqllwxyvkmlemdjwvdwldsflalyjiensslylwmxnkglymlomilmmlyfelklwenwzdwnmfkdfnmndwnwmglplffjzl
Mu: 1, Sh: 20, M: rxkqskvwuivihuemecvvknlocvlfewmjfkxmevcleckieupkwisekmlmevcliespelmlslmcvwmjfkxmvmllfkeiokjhimvlknlhkllkxwivpkkvwxujlkdlcivucvkcrekzkxihdmrrkxkvlwmjfkxlknlhkllkxedkjkvdmvycvmlejcemlmcvmvlfkokeeiyk
Mu: 1, Sh: 21, M: qwjprjuvthuhgtdldbuujmknbukedvliejwldubkdbjhdtojvhrdjlkldubkhdrodklkrklbuvliejwlulkkejdhnjighlukjmkgjkkjwvhuojjuvwtikjckbhutbujbqdjyjwhgclqqjwjukvliejwkjmkgjkkjwdcjijucluxbulkdibdlklbulukejnjddhxj
Mu: 1, Sh: 22, M: pvioqitusgtgfsckcattiljmatjdcukhdivkctajcaigcsniugqcikjkctajgcqncjkjqjkatukhdivktkjjdicgmihfgktjiljfijjivugtniituvshjibjagtsatiapcixivgfbkppivitjukhdivjiljfijjivcbihitbktwatkjchackjkatktjdimiccgwi
Mu: 1, Sh: 23, M: ouhnphstrfsferbjbzsshkilzsicbtjgchujbszibzhfbrmhtfpbhjijbszifbpmbijipijzstjgchujsjiichbflhgefjsihkiehiihutfsmhhsturgihaizfsrzshzobhwhufeajoohuhsitjgchuihkiehiihubahghsajsvzsjibgzbjijzsjsichlhbbfvh
Mu: 1, Sh: 24, M: ntgmogrsqeredqaiayrrgjhkyrhbasifbgtiaryhaygeaqlgseoagihiaryheaolahihohiyrsifbgtirihhbgaekgfdeirhgjhdghhgtserlggrstqfhgzhyerqyrgynagvgtedzinngtgrhsifbgthgjhdghhgtazgfgrziruyrihafyaihiyrirhbgkgaaeug
Mu: 1, Sh: 25, M: msflnfqrpdqdcpzhzxqqfigjxqgazrheafshzqxgzxfdzpkfrdnzfhghzqxgdznkzghgnghxqrheafshqhggafzdjfecdhqgfigcfggfsrdqkffqrspegfygxdqpxqfxmzfufsdcyhmmfsfqgrheafsgfigcfggfszyfefqyhqtxqhgzexzhghxqhqgafjfzzdtf
Mu: 3, Sh: 0, M: vxkmekfowsfsjwiciqffkltuqftriocbrkxcifqtiqksiwdkoseikctcifqtsieditctetcqfocbrkxcfcttrkisukbjscftkltjkttkxosfdkkfoxwbtkztqsfwqfkqvikpkxsjzcvvkxkftocbrkxtkltjkttkxizkbkfzcfgqfctibqictcqfcftrkukiisgk
Mu: 3, Sh: 1, M: mobdvbwfnjwjanztzhwwbcklhwkizftsibotzwhkzhbjznubfjvzbtktzwhkjzvuzktkvkthwftsibotwtkkibzjlbsajtwkbckabkkbofjwubbwfonskbqkhjwnhwbhmzbgbojaqtmmbobwkftsibokbckabkkbozqbsbwqtwxhwtkzshztkthwtwkiblbzzjxb
Mu: 3, Sh: 2, M: dfsumsnweanareqkqynnstbcynbzqwkjzsfkqnybqysaqelswamqskbkqnybaqmlqbkbmbkynwkjzsfknkbbzsqacsjraknbstbrsbbsfwanlssnwfejbshbyaneynsydqsxsfarhkddsfsnbwkjzsfbstbrsbbsfqhsjsnhknoynkbqjyqkbkynknbzscsqqaos
Mu: 3, Sh: 3, M: uwjldjenvrerivhbhpeejkstpesqhnbaqjwbhepshpjrhvcjnrdhjbsbhepsrhdchsbsdsbpenbaqjwbebssqjhrtjairbesjksijssjwnrecjjenwvasjysprevpejpuhjojwriybuujwjesnbaqjwsjksijssjwhyjajeybefpebshaphbsbpebesqjtjhhrfj
Mu: 3, Sh: 4, M: lnacuavemivizmysygvvabjkgvjhyesrhansyvgjygaiymtaeiuyasjsyvgjiyutyjsjujsgvesrhansvsjjhayikarzisvjabjzajjaneivtaavenmrjapjgivmgvaglyafanizpsllanavjesrhanjabjzajjanyparavpsvwgvsjyrgysjsgvsvjhakayyiwa
Mu: 3, Sh: 5, M: certlrmvdzmzqdpjpxmmrsabxmaypvjiyrejpmxapxrzpdkrvzlprjajpmxazplkpajalajxmvjiyrejmjaayrpzbriqzjmarsaqraarevzmkrrmvediargaxzmdxmrxcprwrezqgjccrermavjiyrearsaqraarepgrirmgjmnxmjapixpjajxmjmayrbrppznr
Mu: 3, Sh: 6, M: tvikcidmuqdqhugagoddijrsodrpgmazpivagdorgoiqgubimqcgiaragdorqgcbgrarcraodmazpivadarrpigqsizhqadrijrhirrivmqdbiidmvuzrixroqduodiotginivqhxattividrmazpivrijrhirrivgxizidxadeodargzogaraodadrpisiggqei
Mu: 3, Sh: 7, M: kmzbtzudlhuhylxrxfuuzaijfuigxdrqgzmrxufixfzhxlszdhtxzrirxufihxtsxiritirfudrqgzmruriigzxhjzqyhruizaiyziizmdhuszzudmlqizoifhulfuzfkxzezmhyorkkzmzuidrqgzmizaiyziizmxozqzuoruvfurixqfxrirfuruigzjzxxhvz
Mu: 3, Sh: 8, M: bdqskqlucylypcoiowllqrzawlzxouihxqdiolwzowqyocjquykoqiziolwzyokjozizkziwluihxqdilizzxqoyaqhpyilzqrzpqzzqduyljqqludchzqfzwylcwlqwboqvqdypfibbqdqlzuihxqdzqrzpqzzqdofqhqlfilmwlizohwoiziwlilzxqaqooymq
Mu: 3, Sh: 9, M: suhjbhcltpcpgtfzfncchiqrncqoflzyohuzfcnqfnhpftahlpbfhzqzfcnqpfbafqzqbqznclzyohuzczqqohfprhygpzcqhiqghqqhulpcahhclutyqhwqnpctnchnsfhmhupgwzsshuhcqlzyohuqhiqghqqhufwhyhcwzcdnczqfynfzqznczcqohrhffpdh
Mu: 3, Sh: 10, M: jlyasytckgtgxkwqwettyzhiethfwcqpfylqwtehweygwkrycgswyqhqwtehgwsrwhqhshqetcqpfylqtqhhfywgiypxgqthyzhxyhhylcgtryytclkphynhegtketyejwydylgxnqjjylythcqpfylhyzhxyhhylwnypytnqtuetqhwpewqhqetqthfyiywwguy
Mu: 3, Sh: 11, M: acprjpktbxkxobnhnvkkpqyzvkywnthgwpchnkvynvpxnbiptxjnphyhnkvyxnjinyhyjyhvkthgwpchkhyywpnxzpgoxhkypqyopyypctxkippktcbgypeyvxkbvkpvanpupcxoehaapcpkythgwpcypqyopyypcnepgpkehklvkhyngvnhyhvkhkywpzpnnxlp
Mu: 3, Sh: 12, M: rtgiagbksobofseyembbghpqmbpnekyxngtyebmpemgoeszgkoaegypyebmpoeazepypapymbkyxngtybyppngeoqgxfoybpghpfgppgtkobzggbktsxpgvpmobsmbgmreglgtofvyrrgtgbpkyxngtpghpfgppgtevgxgbvybcmbypexmeypymbybpngqgeeocg
Mu: 3, Sh: 13, M: ikxzrxsbjfsfwjvpvdssxyghdsgevbpoexkpvsdgvdxfvjqxbfrvxpgpvsdgfvrqvgpgrgpdsbpoexkpspggexvfhxowfpsgxygwxggxkbfsqxxsbkjogxmgdfsjdsxdivxcxkfwmpiixkxsgbpoexkgxygwxggxkvmxoxsmpstdspgvodvpgpdspsgexhxvvftx
Mu: 3, Sh: 14, M: zboqiojsawjwnamgmujjopxyujxvmsgfvobgmjuxmuowmahoswimogxgmjuxwmihmxgxixgujsgfvobgjgxxvomwyofnwgjxopxnoxxobswjhoojsbafxodxuwjaujouzmotobwndgzzobojxsgfvobxopxnoxxobmdofojdgjkujgxmfumgxgujgjxvoyommwko
Mu: 3, Sh: 15, M: qsfhzfajrnanerdxdlaafgoplaomdjxwmfsxdalodlfndryfjnzdfxoxdalondzydoxozoxlajxwmfsxaxoomfdnpfwenxaofgoefoofsjnayffajsrwofuolnarlaflqdfkfsneuxqqfsfaojxwmfsofgoefoofsdufwfauxablaxodwldxoxlaxaomfpfddnbf
Mu: 3, Sh: 16, M: hjwyqwraiereviuoucrrwxfgcrfduaondwjourcfucweuipwaequwofourcfeuqpufofqfocraondwjoroffdwuegwnveorfwxfvwffwjaerpwwrajinfwlfcericrwchuwbwjevlohhwjwrfaondwjfwxfvwffwjulwnwrlorscrofuncuofocrorfdwgwuuesw
Mu: 3, Sh: 17, M: yanphnirzvivmzlfltiinowxtiwulrfeunaflitwltnvlzgnrvhlnfwflitwvlhglwfwhwftirfeunafifwwunlvxnemvfiwnowmnwwnarvignnirazewncwtviztintylnsnavmcfyynaniwrfeunawnowmnwwnalcnenicfijtifwletlfwftifiwunxnllvjn
Mu: 3, Sh: 18, M: pregyeziqmzmdqcwckzzefnokznlciwvlerwczknckemcqxeimycewnwczknmcyxcnwnynwkziwvlerwzwnnlecmoevdmwznefndennerimzxeezirqvnetnkmzqkzekpcejermdtwpperezniwvlernefndennercteveztwzakzwncvkcwnwkzwznleoeccmae
Mu: 3, Sh: 19, M: givxpvqzhdqduhtntbqqvwefbqectznmcvintqbetbvdthovzdptvnentqbedtpotenepenbqznmcvinqneecvtdfvmudnqevweuveevizdqovvqzihmevkebdqhbqvbgtvaviduknggvivqeznmcvievweuveevitkvmvqknqrbqnetmbtnenbqnqecvfvttdrv
Mu: 3, Sh: 20, M: xzmogmhqyuhulykekshhmnvwshvtkqedtmzekhsvksmukyfmqugkmevekhsvukgfkvevgveshqedtmzehevvtmkuwmdluehvmnvlmvvmzquhfmmhqzydvmbvsuhyshmsxkmrmzulbexxmzmhvqedtmzvmnvlmvvmzkbmdmhbehishevkdskeveshehvtmwmkkuim
Mu: 3, Sh: 21, M: oqdfxdyhplylcpbvbjyydemnjymkbhvukdqvbyjmbjdlbpwdhlxbdvmvbyjmlbxwbmvmxmvjyhvukdqvyvmmkdblnduclvymdemcdmmdqhlywddyhqpumdsmjlypjydjobdidqlcsvoodqdymhvukdqmdemcdmmdqbsdudysvyzjyvmbujbvmvjyvymkdndbblzd
Mu: 3, Sh: 22, M: fhuwoupygcpctgsmsappuvdeapdbsymlbuhmspadsaucsgnuycosumdmspadcsonsdmdodmapymlbuhmpmddbusceultcmpduvdtudduhycpnuupyhgldujdacpgapuafsuzuhctjmffuhupdymlbuhduvdtudduhsjulupjmpqapmdslasmdmapmpdbueusscqu
Mu: 3, Sh: 23, M: wylnflgpxtgtkxjdjrgglmuvrgusjpdcslydjgrujrltjxelptfjldudjgrutjfejudufudrgpdcslydgduusljtvlcktdgulmukluulyptgellgpyxculaurtgxrglrwjlqlytkadwwlylgupdcslyulmukluulyjalclgadghrgdujcrjdudrgdguslvljjthl
Mu: 3, Sh: 24, M: npcewcxgokxkboauaixxcdlmixljagutjcpuaxilaickaovcgkwaculuaxilkawvalulwluixgutjcpuxulljcakmctbkuxlcdlbcllcpgkxvccxgpotlcrlikxoixcinachcpkbrunncpcxlgutjcplcdlbcllcparctcxruxyixulatiauluixuxljcmcaakyc
Mu: 3, Sh: 25, M: egtvntoxfbobsfrlrzootucdzocarxlkatglrozcrztbrfmtxbnrtlclrozcbrnmrclcnclzoxlkatglolccatrbdtksbloctucstcctgxbomttoxgfkcticzbofzotzertytgbsileetgtocxlkatgctucstcctgritktoilopzolcrkzrlclzolocatdtrrbpt
Mu: 5, Sh: 0, M: xtgcsgdyiqdqvikwkuddgrbmudbfkywlfgtwkdubkugqkihgyqskgwbwkdubqkshkbwbsbwudywlfgtwdwbbfgkqmglvqwdbgrbvgbbgtyqdhggdytilbgpbuqdiudguxkgjgtqvpwxxgtgdbywlfgtbgrbvgbbgtkpglgdpwdoudwbklukwbwudwdbfgmgkkqog
Mu: 5, Sh: 1, M: cylhxlidnvivanpbpziilwgrzigkpdbqklybpizgpzlvpnmldvxplbgbpizgvpxmpgbgxgbzidbqklybibggklpvrlqavbiglwgalgglydvimllidynqglugzvinzilzcplolyvaubcclyligdbqklyglwgalgglypulqliubitzibgpqzpbgbzibigklrlppvtl
Mu: 5, Sh: 2, M: hdqmcqnisanafsuguennqblwenlpuigvpqdgunelueqausrqiacuqglgunelaucrulglclgenigvpqdgngllpquawqvfagnlqblfqllqdianrqqnidsvlqzleansenqehuqtqdafzghhqdqnligvpqdlqblfqllqduzqvqnzgnyengluveuglgengnlpqwquuayq
Mu: 5, Sh: 3, M: mivrhvsnxfsfkxzlzjssvgqbjsquznlauvilzsjqzjvfzxwvnfhzvlqlzsjqfzhwzqlqhqljsnlauvilslqquvzfbvakflsqvgqkvqqvinfswvvsnixaqveqjfsxjsvjmzvyvifkelmmvivsqnlauviqvgqkvqqvizevavselsdjslqzajzlqljslsquvbvzzfdv
Mu: 5, Sh: 4, M: rnawmaxsckxkpceqeoxxalvgoxvzesqfzanqexoveoakecbaskmeaqvqexovkembevqvmvqoxsqfzanqxqvvzaekgafpkqxvalvpavvanskxbaaxsncfvajvokxcoxaoreadankpjqrranaxvsqfzanvalvpavvanejafaxjqxioxqvefoeqvqoxqxvzagaeekia
Mu: 5, Sh: 5, M: wsfbrfcxhpcpuhjvjtccfqaltcaejxvkefsvjctajtfpjhgfxprjfvavjctapjrgjavaravtcxvkefsvcvaaefjplfkupvcafqaufaafsxpcgffcxshkafoatpchtcftwjfifspuovwwfsfcaxvkefsafqaufaafsjofkfcovcntcvajktjvavtcvcaeflfjjpnf
Mu: 5, Sh: 6, M: bxkgwkhcmuhuzmoaoyhhkvfqyhfjocapjkxaohyfoykuomlkcuwokafaohyfuowlofafwfayhcapjkxahaffjkouqkpzuahfkvfzkffkxcuhlkkhcxmpfktfyuhmyhkyboknkxuztabbkxkhfcapjkxfkvfzkffkxotkpkhtahsyhafopyoafayhahfjkqkoousk
Mu: 5, Sh: 7, M: gcplbpmhrzmzertftdmmpakvdmkothfuopcftmdktdpztrqphzbtpfkftmdkztbqtkfkbkfdmhfuopcfmfkkoptzvpuezfmkpakepkkpchzmqppmhcrukpykdzmrdmpdgtpspczeyfggpcpmkhfuopckpakepkkpctypupmyfmxdmfktudtfkfdmfmkopvpttzxp
Mu: 5, Sh: 8, M: lhuqgurmwerejwykyirrufpairptymkztuhkyripyiueywvumegyukpkyripeygvypkpgpkirmkztuhkrkpptuyeauzjekrpufpjuppuhmervuurmhwzpudpierwiruilyuxuhejdklluhurpmkztuhpufpjuppuhyduzurdkrcirkpyziykpkirkrptuauyyecu
Mu: 5, Sh: 9, M: qmzvlzwrbjwjobdpdnwwzkufnwuydrpeyzmpdwnudnzjdbazrjldzpupdwnujdladupulupnwrpeyzmpwpuuyzdjfzeojpwuzkuozuuzmrjwazzwrmbeuziunjwbnwznqdzczmjoipqqzmzwurpeyzmuzkuozuuzmdizezwipwhnwpudendpupnwpwuyzfzddjhz
Mu: 5, Sh: 10, M: vreaqebwgobotgiuisbbepzksbzdiwujderuibsziseoigfewoqieuzuibszoiqfizuzqzusbwujderubuzzdeiokejtoubzepztezzerwobfeebwrgjzenzsobgsbesvieherotnuvverebzwujderzepztezzerinejebnubmsbuzijsiuzusbubzdekeiiome
Mu: 5, Sh: 11, M: awjfvjgbltgtylnznxggjuepxgeinbzoijwzngxenxjtnlkjbtvnjzezngxetnvknezevezxgbzoijwzgzeeijntpjoytzgejueyjeejwbtgkjjgbwloejsextglxgjxanjmjwtyszaajwjgebzoijwejueyjeejwnsjojgszgrxgzenoxnzezxgzgeijpjnntrj
Mu: 5, Sh: 12, M: fbokaolgqylydqsescllozjucljnsgetnobeslcjscoysqpogyasoejeslcjysapsjejajeclgetnobelejjnosyuotdyeljozjdojjobgylpoolgbqtjoxjcylqclocfsorobydxeffoboljgetnobjozjdojjobsxotolxelwclejstcsejecleljnouossywo
Mu: 5, Sh: 13, M: kgtpftqlvdqdivxjxhqqteozhqosxljystgjxqhoxhtdxvutldfxtjojxqhodxfuxojofojhqljystgjqjoostxdztyidjqoteoitootgldquttqlgvyotcohdqvhqthkxtwtgdicjkktgtqoljystgoteoitootgxctytqcjqbhqjoxyhxjojhqjqostztxxdbt
Mu: 5, Sh: 14, M: plyukyvqaivinacocmvvyjtemvtxcqodxylocvmtcmyicazyqikcyotocvmtickzctotktomvqodxylovottxycieydniovtyjtnyttylqivzyyvqladtyhtmivamvympcybylinhoppylyvtqodxyltyjtnyttylchydyvhovgmvotcdmcotomvovtxyeyccigy
Mu: 5, Sh: 15, M: uqdzpdavfnansfhthraadoyjraychvticdqtharyhrdnhfedvnphdtytharynhpehytypytravticdqtatyycdhnjdisntaydoysdyydqvnaeddavqfiydmyrnafradruhdgdqnsmtuudqdayvticdqydoysdyydqhmdidamtalratyhirhtytrataycdjdhhnld
Mu: 5, Sh: 16, M: zvieuifaksfsxkmymwffitdowfdhmaynhivymfwdmwismkjiasumiydymfwdsmujmdydudywfaynhivyfyddhimsoinxsyfditdxiddivasfjiifavkndirdwsfkwfiwzmilivsxryzzivifdaynhivditdxiddivmrinifryfqwfydmnwmydywfyfdhioimmsqi
Mu: 5, Sh: 17, M: eanjznkfpxkxcprdrbkknyitbkimrfdsmnadrkbirbnxrponfxzrndidrkbixrzoridizidbkfdsmnadkdiimnrxtnscxdkinyicniinafxkonnkfapsinwibxkpbknbernqnaxcwdeenankifdsmnainyicniinarwnsnkwdkvbkdirsbrdidbkdkimntnrrxvn
Mu: 5, Sh: 18, M: jfsoespkucpchuwiwgppsdnygpnrwkixrsfiwpgnwgscwutskcewsiniwpgncwetwninenigpkixrsfipinnrswcysxhcipnsdnhsnnsfkcptsspkfuxnsbngcpugpsgjwsvsfchbijjsfspnkixrsfnsdnhsnnsfwbsxspbipagpinwxgwinigpipnrsyswwcas
Mu: 5, Sh: 19, M: okxtjxupzhuhmzbnbluuxisdluswbpncwxknbulsblxhbzyxphjbxnsnbulshbjybsnsjsnlupncwxknunsswxbhdxcmhnusxismxssxkphuyxxupkzcsxgslhuzluxlobxaxkhmgnooxkxuspncwxksxismxssxkbgxcxugnuflunsbclbnsnlunuswxdxbbhfx
Mu: 5, Sh: 20, M: tpcyoczuemzmregsgqzzcnxiqzxbgushbcpsgzqxgqcmgedcumogcsxsgzqxmgodgxsxoxsqzushbcpszsxxbcgmichrmszxcnxrcxxcpumzdcczupehxclxqmzeqzcqtgcfcpmrlsttcpczxushbcpxcnxrcxxcpglchczlszkqzsxghqgsxsqzszxbcicggmkc
Mu: 5, Sh: 21, M: yuhdthezjrerwjlxlveehscnvecglzxmghuxlevclvhrljihzrtlhxcxlevcrltilcxctcxvezxmghuxexccghlrnhmwrxechscwhcchuzreihhezujmchqcvrejvehvylhkhurwqxyyhuheczxmghuchscwhcchulqhmheqxepvexclmvlxcxvexecghnhllrph
Mu: 5, Sh: 22, M: dzmiymjeowjwboqcqajjmxhsajhlqecrlmzcqjahqamwqonmewyqmchcqjahwqynqhchyhcajecrlmzcjchhlmqwsmrbwcjhmxhbmhhmzewjnmmjezorhmvhawjoajmadqmpmzwbvcddmzmjhecrlmzhmxhbmhhmzqvmrmjvcjuajchqraqchcajcjhlmsmqqwum
Mu: 5, Sh: 23, M: ierndrojtbobgtvhvfoorcmxfomqvjhwqrehvofmvfrbvtsrjbdvrhmhvofmbvdsvmhmdmhfojhwqrehohmmqrvbxrwgbhomrcmgrmmrejbosrrojetwmramfbotforfivrurebgahiireromjhwqremrcmgrmmrevarwroahozfohmvwfvhmhfohomqrxrvvbzr
Mu: 5, Sh: 24, M: njwsiwtoygtglyamakttwhrcktrvaombvwjmatkrakwgayxwogiawmrmatkrgaixarmrirmktombvwjmtmrrvwagcwblgmtrwhrlwrrwjogtxwwtojybrwfrkgtyktwknawzwjglfmnnwjwtrombvwjrwhrlwrrwjafwbwtfmtektmrabkamrmktmtrvwcwaagew
Mu: 5, Sh: 25, M: sobxnbytdlylqdfrfpyybmwhpywaftrgaborfypwfpblfdcbtlnfbrwrfypwlfncfwrwnwrpytrgaboryrwwabflhbgqlrywbmwqbwwbotlycbbytodgwbkwplydpybpsfbebolqkrssbobywtrgabowbmwqbwwbofkbgbykryjpyrwfgpfrwrpyrywabhbffljb
Mu: 7, Sh: 0, M: jviuyirgcerepcwmwsrribxqsrxlwgmtlivmwrsxwsiewcfigeywimxmwrsxewyfwxmxyxmsrgmtlivmrmxxliweqitpemrxibxpixxivgerfiirgvctxihxsercsrisjwizivephmjjivirxgmtlivxibxpixxivwhitirhmrksrmxwtswmxmsrmrxliqiwweki
Mu: 7, Sh: 1, M: ugtfjtcrnpcpanhxhdcctmibdciwhrxewtgxhcdihdtphnqtrpjhtxixhcdiphjqhixijixdcrxewtgxcxiiwthpbteapxcitmiatiitgrpcqttcrgneitsidpcndctduhtktgpasxuutgtcirxewtgitmiatiitghstetcsxcvdcxihedhxixdcxciwtbthhpvt
Mu: 7, Sh: 2, M: frequencyanalysisonnextmonthscipherisnotsoeasybecauseitisnotasubstitutioncipherinitthesameplaintextlettercanbeencryptedtoanyoneofseveraldifferentciphertextlettersdependingonitspositioninthemessage
Mu: 7, Sh: 3, M: qcpbfpynjlylwjdtdzyypiexzyesdntaspctdyzedzpldjmpnlfdptetdyzeldfmdetefetzyntaspctyteespdlxpawltyepiewpeepcnlymppyncjaepoezlyjzypzqdpgpclwotqqpcpyentaspcepiewpeepcdopapyotyrzytedazdtetzytyespxpddlrp
Mu: 7, Sh: 4, M: bnamqajyuwjwhuoeokjjatpikjpdoyeldaneojkpokawouxaywqoaepeojkpwoqxopepqpekjyeldanejeppdaowialhwejpatphappanywjxaajynulpazpkwjukjakboaranwhzebbanajpyeldanpatphappanozalajzejckjepolkoepekjejpdaiaoowca
Mu: 7, Sh: 5, M: mylxblujfhuhsfzpzvuuleatvuaozjpwolypzuvazvlhzfiljhbzlpapzuvahzbizapabapvujpwolypupaaolzhtlwshpualeaslaalyjhuillujyfwalkavhufvulvmzlclyhskpmmlyluajpwolyaleaslaalyzklwlukpunvupazwvzpapvupuaoltlzzhnl
Mu: 7, Sh: 6, M: xjwimwfuqsfsdqkakgffwplegflzkuahzwjakfglkgwskqtwusmkwalakfglskmtklalmlagfuahzwjafallzwksewhdsaflwpldwllwjusftwwfujqhlwvlgsfqgfwgxkwnwjsdvaxxwjwfluahzwjlwpldwllwjkvwhwfvafygfalkhgkalagfaflzwewkksyw
Mu: 7, Sh: 7, M: iuhtxhqfbdqdobvlvrqqhawprqwkvflskhulvqrwvrhdvbehfdxvhlwlvqrwdvxevwlwxwlrqflskhulqlwwkhvdphsodlqwhawohwwhufdqehhqfubswhgwrdqbrqhrivhyhudogliihuhqwflskhuwhawohwwhuvghshqglqjrqlwvsrvlwlrqlqwkhphvvdjh
Mu: 7, Sh: 8, M: tfseisbqmobozmgwgcbbslhacbhvgqwdvsfwgbchgcsogmpsqoigswhwgbchogipghwhihwcbqwdvsfwbwhhvsgoasdzowbhslhzshhsfqobpssbqfmdhsrhcobmcbsctgsjsfozrwttsfsbhqwdvsfhslhzshhsfgrsdsbrwbucbwhgdcgwhwcbwbhvsasggous
Mu: 7, Sh: 9, M: eqdptdmbxzmzkxrhrnmmdwslnmsgrbhogdqhrmnsrndzrxadbztrdhshrmnszrtarshstshnmbhogdqhmhssgdrzldokzhmsdwskdssdqbzmaddmbqxosdcsnzmxnmdnerdudqzkcheedqdmsbhogdqsdwskdssdqrcdodmchmfnmhsronrhshnmhmsgdldrrzfd
Mu: 7, Sh: 10, M: pboaeoxmikxkvicscyxxohdwyxdrcmszrobscxydcyokcilomkecosdscxydkcelcdsdedsyxmszrobsxsddrockwozvksxdohdvoddobmkxlooxmbizdondykxiyxoypcofobkvnsppoboxdmszrobdohdvoddobcnozoxnsxqyxsdczycsdsyxsxdrowocckqo
Mu: 7, Sh: 11, M: amzlpzixtvivgtndnjiizsohjiocnxdkczmdnijonjzvntwzxvpnzdodnijovnpwnodopodjixdkczmdidoocznvhzkgvdiozsogzoozmxviwzzixmtkozyojvitjizjanzqzmvgydaazmzioxdkczmozsogzoozmnyzkziydibjidonkjndodjidioczhznnvbz
Mu: 7, Sh: 12, M: lxkwaktiegtgreyoyuttkdzsutznyiovnkxoytuzyukgyehkigaykozoytuzgyahyzozazoutiovnkxotozznkygskvrgotzkdzrkzzkxigthkktixevzkjzugteutkulykbkxgrjollkxktziovnkxzkdzrkzzkxyjkvktjotmutozyvuyozoutotznkskyygmk
Mu: 7, Sh: 13, M: wivhlvetprercpjzjfeevokdfekyjtzgyvizjefkjfvrjpsvtrljvzkzjefkrjlsjkzklkzfetzgyvizezkkyvjrdvgcrzekvokcvkkvitresvvetipgkvukfrepfevfwjvmvircuzwwvivektzgyvikvokcvkkvijuvgveuzexfezkjgfjzkzfezekyvdvjjrxv
Mu: 7, Sh: 14, M: htgswgpeacpcnaukuqppgzvoqpvjuekrjgtkupqvuqgcuadgecwugkvkupqvcuwduvkvwvkqpekrjgtkpkvvjgucogrnckpvgzvngvvgtecpdggpetarvgfvqcpaqpgqhugxgtcnfkhhgtgpvekrjgtvgzvngvvgtufgrgpfkpiqpkvurqukvkqpkpvjgoguucig
Mu: 7, Sh: 15, M: serdhraplnanylfvfbaarkgzbagufpvcurevfabgfbrnflorpnhfrvgvfabgnfhofgvghgvbapvcurevavggurfnzrcynvagrkgyrggrepnaorrapelcgrqgbnalbarbsfrirenyqvssreragpvcuregrkgyrggrefqrcraqvatbavgfcbfvgvbavagurzrffntr
Mu: 7, Sh: 16, M: dpcosclawylyjwqgqmllcvrkmlrfqagnfcpgqlmrqmcyqwzcaysqcgrgqlmryqszqrgrsrgmlagnfcpglgrrfcqykcnjyglrcvrjcrrcpaylzcclapwnrcbrmylwmlcmdqctcpyjbgddcpclragnfcprcvrjcrrcpqbcnclbglemlgrqnmqgrgmlglrfckcqqyec
Mu: 7, Sh: 17, M: oanzdnwlhjwjuhbrbxwwngcvxwcqblryqnarbwxcbxnjbhknljdbnrcrbwxcjbdkbcrcdcrxwlryqnarwrccqnbjvnyujrwcngcunccnaljwknnwlahycnmcxjwhxwnxobnenajumroonanwclryqnacngcunccnabmnynwmrwpxwrcbyxbrcrxwrwcqnvnbbjpn
Mu: 7, Sh: 18, M: zlykoyhwsuhufsmcmihhyrngihnbmwcjbylcmhinmiyumsvywuomycncmhinumovmncnoncihwcjbylchcnnbymugyjfuchnyrnfynnylwuhvyyhwlsjnyxniuhsihyizmypylufxczzylyhnwcjbylnyrnfynnylmxyjyhxchaihcnmjimcncihchnbygymmuay
Mu: 7, Sh: 19, M: kwjvzjshdfsfqdxnxtssjcyrtsymxhnumjwnxstyxtjfxdgjhfzxjnynxstyfxzgxynyzyntshnumjwnsnyymjxfrjuqfnsyjcyqjyyjwhfsgjjshwduyjiytfsdtsjtkxjajwfqinkkjwjsyhnumjwyjcyqjyyjwxijujsinsltsnyxutxnyntsnsymjrjxxflj
Mu: 7, Sh: 20, M: vhugkudsoqdqboiyieddunjcedjxisyfxuhyidejieuqiorusqkiuyjyidejqikrijyjkjyedsyfxuhydyjjxuiqcufbqydjunjbujjuhsqdruudshofjutjeqdoedueviuluhqbtyvvuhudjsyfxuhjunjbujjuhitufudtydwedyjifeiyjyedydjxucuiiqwu
Mu: 7, Sh: 21, M: gsfrvfodzbobmztjtpoofyunpouitdjqifsjtoputpfbtzcfdbvtfjujtopubtvctujuvujpodjqifsjojuuiftbnfqmbjoufyumfuufsdbocffodszqufeupbozpofpgtfwfsbmejggfsfoudjqifsufyumfuufstefqfoejohpojutqptjujpojouifnfttbhf
Mu: 7, Sh: 22, M: rdqcgqzokmzmxkeueazzqjfyazfteoubtqduezafeaqmeknqomgequfuezafmegnefufgfuazoubtqduzufftqemyqbxmuzfqjfxqffqdomznqqzodkbfqpfamzkazqareqhqdmxpurrqdqzfoubtqdfqjfxqffqdepqbqzpuzsazufebaeufuazuzftqyqeemsq
Mu: 7, Sh: 23, M: cobnrbkzvxkxivpfplkkbuqjlkqepzfmebofpklqplbxpvybzxrpbfqfpklqxprypqfqrqflkzfmebofkfqqebpxjbmixfkqbuqibqqbozxkybbkzovmqbaqlxkvlkblcpbsboxiafccbobkqzfmeboqbuqibqqbopabmbkafkdlkfqpmlpfqflkfkqebjbppxdb
Mu: 7, Sh: 24, M: nzmycmvkgivitgaqawvvmfbuwvbpakqxpmzqavwbawmiagjmkicamqbqavwbiacjabqbcbqwvkqxpmzqvqbbpmaiumxtiqvbmfbtmbbmzkivjmmvkzgxbmlbwivgwvmwnamdmzitlqnnmzmvbkqxpmzbmfbtmbbmzalmxmvlqvowvqbaxwaqbqwvqvbpmumaaiom
Mu: 7, Sh: 25, M: ykxjnxgvrtgterlblhggxqmfhgmalvbiaxkblghmlhxtlruxvtnlxbmblghmtlnulmbmnmbhgvbiaxkbgbmmaxltfxietbgmxqmexmmxkvtguxxgvkrimxwmhtgrhgxhylxoxktewbyyxkxgmvbiaxkmxqmexmmxklwxixgwbgzhgbmlihlbmbhgbgmaxfxlltzx
Mu: 9, Sh: 0, M: hzmekmtwqgtgdqusuottmvpyotpxuwsjxmzsutopuomguqbmwgkumspsutopgukbupspkpsotwsjxmzstsppxmugymjdgstpmvpdmppmzwgtbmmtwzqjpmrpogtqotmohumfmzgdrshhmzmtpwsjxmzpmvpdmppmzurmjmtrstcotspujouspsotstpxmymuugcm
Mu: 9, Sh: 1, M: ewjbhjqtndqdanrprlqqjsmvlqmurtpgujwprqlmrljdrnyjtdhrjpmprqlmdrhyrmpmhmplqtpgujwpqpmmujrdvjgadpqmjsmajmmjwtdqyjjqtwngmjomldqnlqjlerjcjwdaopeejwjqmtpgujwmjsmajmmjwrojgjqopqzlqpmrglrpmplqpqmujvjrrdzj
Mu: 9, Sh: 2, M: btgyegnqkanaxkomoinngpjsinjroqmdrgtmonijoigaokvgqaeogmjmonijaoevojmjejminqmdrgtmnmjjrgoasgdxamnjgpjxgjjgtqanvggnqtkdjgljiankingibogzgtaxlmbbgtgnjqmdrgtjgpjxgjjgtolgdgnlmnwinmjodiomjminmnjrgsgooawg
Mu: 9, Sh: 3, M: yqdvbdknhxkxuhljlfkkdmgpfkgolnjaodqjlkfglfdxlhsdnxbldjgjlkfgxlbslgjgbgjfknjaodqjkjggodlxpdauxjkgdmgudggdqnxksddknqhagdigfxkhfkdfyldwdqxuijyydqdkgnjaodqgdmgudggdqlidadkijktfkjglafljgjfkjkgodpdllxtd
Mu: 9, Sh: 4, M: vnasyahkeuhureigichhajdmchdlikgxlangihcdicauiepakuyiagdgihcduiypidgdydgchkgxlanghgddlaiumaxrughdajdraddankuhpaahknexdafdcuhechacviatanurfgvvanahdkgxlandajdraddanifaxahfghqchgdixcigdgchghdlamaiiuqa
Mu: 9, Sh: 5, M: skxpvxehbrerobfdfzeexgajzeaifhduixkdfezafzxrfbmxhrvfxdadfezarfvmfadavadzehduixkdedaaixfrjxuordeaxgaoxaaxkhremxxehkbuaxcazrebzexzsfxqxkrocdssxkxeahduixkaxgaoxaaxkfcxuxecdenzedafuzfdadzedeaixjxffrnx
Mu: 9, Sh: 6, M: phumsubeyobolycacwbbudxgwbxfcearfuhacbwxcwuocyjueoscuaxacbwxocsjcxaxsxawbearfuhabaxxfucogurloabxudxluxxuheobjuubehyrxuzxwobywbuwpcunuholzappuhubxearfuhxudxluxxuhczurubzabkwbaxcrwcaxawbabxfuguccoku
Mu: 9, Sh: 7, M: merjprybvlylivzxztyyraudtyuczbxocrexzytuztrlzvgrblpzrxuxzytulzpgzuxupuxtybxocrexyxuucrzldroilxyurauiruureblygrrybevourwutlyvtyrtmzrkreliwxmmreryubxocreurauiruurezwrorywxyhtyxuzotzxuxtyxyucrdrzzlhr
Mu: 9, Sh: 8, M: jbogmovysivifswuwqvvoxraqvrzwyulzobuwvqrwqoiwsdoyimwouruwvqriwmdwrurmruqvyulzobuvurrzowiaolfiuvroxrforrobyivdoovybslrotrqivsqvoqjwohobiftujjobovryulzobroxrforrobwtolovtuveqvurwlqwuruqvuvrzoaowwieo
Mu: 9, Sh: 9, M: gyldjlsvpfsfcptrtnssluoxnsowtvriwlyrtsnotnlftpalvfjtlrortsnoftjatorojornsvriwlyrsroowltfxlicfrsoluocloolyvfsallsvypiolqonfspnslngtlelyfcqrgglylsovriwlyoluocloolytqlilsqrsbnsrotintrornsrsowlxlttfbl
Mu: 9, Sh: 10, M: dviagipsmcpczmqoqkppirlukpltqsoftivoqpklqkicqmxiscgqioloqpklcqgxqlolglokpsoftivopolltiqcuifzcoplirlzillivscpxiipsvmflinlkcpmkpikdqibivcznoddiviplsoftivlirlzillivqnifipnopykpolqfkqolokpopltiuiqqcyi
Mu: 9, Sh: 11, M: asfxdfmpjzmzwjnlnhmmfoirhmiqnplcqfslnmhinhfznjufpzdnflilnmhizndunilidilhmplcqfslmliiqfnzrfcwzlmifoiwfiifspzmuffmpsjcifkihzmjhmfhanfyfszwklaafsfmiplcqfsifoiwfiifsnkfcfmklmvhmlinchnlilhmlmiqfrfnnzvf
Mu: 9, Sh: 12, M: xpcuacjmgwjwtgkikejjclfoejfnkmizncpikjefkecwkgrcmwakcifikjefwkarkfifafiejmizncpijiffnckwocztwijfclftcffcpmwjrccjmpgzfchfewjgejcexkcvcpwthixxcpcjfmizncpfclftcffcpkhczcjhijsejifkzekifiejijfncockkwsc
Mu: 9, Sh: 13, M: umzrxzgjdtgtqdhfhbggziclbgckhjfwkzmfhgbchbzthdozjtxhzfcfhgbcthxohcfcxcfbgjfwkzmfgfcckzhtlzwqtfgczicqzcczmjtgozzgjmdwczecbtgdbgzbuhzszmtqefuuzmzgcjfwkzmczicqzcczmhezwzgefgpbgfchwbhfcfbgfgckzlzhhtpz
Mu: 9, Sh: 14, M: rjwouwdgaqdqnaeceyddwfziydzhegcthwjcedyzeywqealwgquewczcedyzqeulezczuzcydgcthwjcdczzhweqiwtnqcdzwfznwzzwjgqdlwwdgjatzwbzyqdaydwyrewpwjqnbcrrwjwdzgcthwjzwfznwzzwjebwtwdbcdmydczetyeczcydcdzhwiweeqmw
Mu: 9, Sh: 15, M: ogtlrtadxnankxbzbvaatcwfvawebdzqetgzbavwbvtnbxitdnrbtzwzbavwnbribwzwrwzvadzqetgzazwwetbnftqknzawtcwktwwtgdnaittadgxqwtywvnaxvatvobtmtgnkyzootgtawdzqetgwtcwktwwtgbytqtayzajvazwbqvbzwzvazawetftbbnjt
Mu: 9, Sh: 16, M: ldqioqxaukxkhuywysxxqztcsxtbyawnbqdwyxstysqkyufqakoyqwtwyxstkyofytwtotwsxawnbqdwxwttbqykcqnhkwxtqzthqttqdakxfqqxaduntqvtskxusxqslyqjqdkhvwllqdqxtawnbqdtqzthqttqdyvqnqxvwxgsxwtynsywtwsxwxtbqcqyykgq
Mu: 9, Sh: 17, M: ianflnuxrhuhervtvpuunwqzpuqyvxtkynatvupqvpnhvrcnxhlvntqtvupqhvlcvqtqlqtpuxtkynatutqqynvhznkehtuqnwqenqqnaxhucnnuxarkqnsqphurpunpivngnahestiinanuqxtkynaqnwqenqqnavsnknustudputqvkpvtqtputuqynznvvhdn
Mu: 9, Sh: 18, M: fxkcikruoerebosqsmrrktnwmrnvsuqhvkxqsrmnsmkesozkueiskqnqsrmnesizsnqninqmruqhvkxqrqnnvksewkhbeqrnktnbknnkxuerzkkruxohnkpnmeromrkmfskdkxebpqffkxkrnuqhvkxnktnbknnkxspkhkrpqramrqnshmsqnqmrqrnvkwksseak
Mu: 9, Sh: 19, M: cuhzfhorlbobylpnpjoohqktjoksprneshunpojkpjhbplwhrbfphnknpojkbpfwpknkfknjorneshunonkkshpbtheybnokhqkyhkkhurbowhhorulekhmkjboljohjcphahubymncchuhokrneshukhqkyhkkhupmhehomnoxjonkpejpnknjonokshthppbxh
Mu: 9, Sh: 20, M: zrewceloiylyvimkmgllenhqglhpmokbperkmlghmgeymiteoycmekhkmlghymctmhkhchkglokbperklkhhpemyqebvyklhenhvehheroylteeloribhejhgyliglegzmexeryvjkzzerelhokbperhenhvehhermjebeljkluglkhmbgmkhkglklhpeqemmyue
Mu: 9, Sh: 21, M: wobtzbilfvivsfjhjdiibkendiemjlhymbohjidejdbvjfqblvzjbhehjidevjzqjehezehdilhymbohiheembjvnbysvhiebkesbeebolviqbbilofyebgedvifdibdwjbubovsghwwbobielhymboebkesbeebojgbybighirdihejydjhehdihiembnbjjvrb
Mu: 9, Sh: 22, M: tlyqwyficsfspcgegaffyhbkafbjgievjylegfabgaysgcnyiswgyebegfabsgwngbebwbeafievjylefebbjygskyvpsefbyhbpybbylisfnyyfilcvbydbasfcafyatgyrylspdettylyfbievjylbyhbpybbylgdyvyfdefoafebgvagebeafefbjykyggsoy
Mu: 9, Sh: 23, M: qivntvcfzpcpmzdbdxccveyhxcygdfbsgvibdcxydxvpdzkvfptdvbybdcxypdtkdybytybxcfbsgvibcbyygvdphvsmpbcyveymvyyvifpckvvcfizsyvayxpczxcvxqdvovipmabqqvivcyfbsgviyveymvyyvidavsvcabclxcbydsxdbybxcbcygvhvddplv
Mu: 9, Sh: 24, M: nfskqszcwmzmjwayauzzsbveuzvdacypdsfyazuvausmawhscmqasyvyazuvmaqhavyvqvyuzcypdsfyzyvvdsamespjmyzvsbvjsvvsfcmzhsszcfwpvsxvumzwuzsunaslsfmjxynnsfszvcypdsfvsbvjsvvsfaxspszxyziuzyvapuayvyuzyzvdsesaamis
Mu: 9, Sh: 25, M: kcphnpwztjwjgtxvxrwwpysbrwsaxzvmapcvxwrsxrpjxtepzjnxpvsvxwrsjxnexsvsnsvrwzvmapcvwvssapxjbpmgjvwspysgpsspczjweppwzctmspusrjwtrwprkxpipcjguvkkpcpwszvmapcspysgpsspcxupmpwuvwfrwvsxmrxvsvrwvwsapbpxxjfp
Mu: 11, Sh: 0, M: blyiuyzsgmzmtgokoczzydrwczrhoskfhylkozcrocymogpysmuoykrkozcrmouporkrurkczskfhylkzkrrhyomwyftmkzrydrtyrrylsmzpyyzslgfryvrcmzgczycboyxylmtvkbbylyzrskfhylrydrtyrrylovyfyzvkzeczkrofcokrkczkzrhywyoomey
Mu: 11, Sh: 1, M: isfpbfgzntgtanvrvjggfkydjgyovzrmofsrvgjyvjftvnwfztbvfryrvgjytvbwvyrybyrjgzrmofsrgryyofvtdfmatrgyfkyafyyfsztgwffgzsnmyfcyjtgnjgfjivfefstacriifsfgyzrmofsyfkyafyyfsvcfmfgcrgljgryvmjvryrjgrgyofdfvvtlf
Mu: 11, Sh: 2, M: pzmwimnguanahucycqnnmrfkqnfvcgytvmzycnqfcqmacudmgaicmyfycnqfacidcfyfifyqngytvmzynyffvmcakmthaynfmrfhmffmzgandmmngzutfmjfqanuqnmqpcmlmzahjyppmzmnfgytvmzfmrfhmffmzcjmtmnjynsqnyfctqcyfyqnynfvmkmccasm
Mu: 11, Sh: 3, M: wgtdptunbhuhobjfjxuutymrxumcjnfactgfjuxmjxthjbktnhpjtfmfjuxmhjpkjmfmpmfxunfactgfufmmctjhrtaohfumtymotmmtgnhukttungbamtqmxhubxutxwjtstghoqfwwtgtumnfactgmtymotmmtgjqtatuqfuzxufmjaxjfmfxufumctrtjjhzt
Mu: 11, Sh: 4, M: dnakwabuioboviqmqebbaftyebtjqumhjanmqbetqeaoqirauowqamtmqbetoqwrqtmtwtmebumhjanmbmttjaqoyahvombtaftvattanuobraabunihtaxteobiebaedqazanovxmddanabtumhjantaftvattanqxahabxmbgebmtqheqmtmebmbtjayaqqoga
Mu: 11, Sh: 5, M: kuhrdhibpvivcpxtxliihmafliaqxbtoqhutxilaxlhvxpyhbvdxhtatxilavxdyxatadatlibtoqhutitaaqhxvfhocvtiahmachaahubviyhhibupoahealviplihlkxhghuvcetkkhuhiabtoqhuahmachaahuxehohietinlitaxolxtatlitiaqhfhxxvnh
Mu: 11, Sh: 6, M: rboykopiwcpcjweaesppothmsphxeiavxobaepshesocewfoickeoahaepshcekfehahkhaspiavxobapahhxoecmovjcaphothjohhobicpfoopibwvholhscpwsposreonobcjlarrobophiavxobhothjohhobelovoplapuspahevseahaspaphxomoeecuo
Mu: 11, Sh: 7, M: yivfrvwpdjwjqdlhlzwwvaotzwoelphcevihlwzolzvjldmvpjrlvhohlwzojlrmlohorohzwphcevihwhooevljtvcqjhwovaoqvoovipjwmvvwpidcovsozjwdzwvzylvuvijqshyyvivwophceviovaoqvoovilsvcvwshwbzwholczlhohzwhwoevtvlljbv
Mu: 11, Sh: 8, M: fpcmycdwkqdqxksosgddchvagdvlswojlcposdgvsgcqsktcwqyscovosdgvqsytsvovyvogdwojlcpodovvlcsqacjxqodvchvxcvvcpwqdtccdwpkjvczvgqdkgdcgfscbcpqxzoffcpcdvwojlcpvchvxcvvcpszcjcdzodigdovsjgsovogdodvlcacssqic
Mu: 11, Sh: 9, M: mwjtfjkdrxkxerzvznkkjochnkcszdvqsjwvzkncznjxzrajdxfzjvcvzkncxzfazcvcfcvnkdvqsjwvkvccsjzxhjqexvkcjocejccjwdxkajjkdwrqcjgcnxkrnkjnmzjijwxegvmmjwjkcdvqsjwcjocejccjwzgjqjkgvkpnkvczqnzvcvnkvkcsjhjzzxpj
Mu: 11, Sh: 10, M: tdqamqrkyerelygcgurrqvjourjzgkcxzqdcgrujguqegyhqkemgqcjcgrujegmhgjcjmjcurkcxzqdcrcjjzqgeoqxlecrjqvjlqjjqdkerhqqrkdyxjqnjueryurqutgqpqdelncttqdqrjkcxzqdjqvjlqjjqdgnqxqrncrwurcjgxugcjcurcrjzqoqggewq
Mu: 11, Sh: 11, M: akxhtxyrflylsfnjnbyyxcqvbyqgnrjegxkjnybqnbxlnfoxrltnxjqjnybqlntonqjqtqjbyrjegxkjyjqqgxnlvxesljyqxcqsxqqxkrlyoxxyrkfeqxuqblyfbyxbanxwxklsujaaxkxyqrjegxkqxcqsxqqxknuxexyujydbyjqnebnjqjbyjyqgxvxnnldx
Mu: 11, Sh: 12, M: hreoaefymsfszmuquiffejxcifxnuyqlnerqufixuiesumveysaueqxqufixsuavuxqxaxqifyqlnerqfqxxneuscelzsqfxejxzexxerysfveefyrmlxebxisfmifeihuederszbqhherefxyqlnerxejxzexxerubelefbqfkifqxuliuqxqifqfxneceuuske
Mu: 11, Sh: 13, M: oylvhlmftzmzgtbxbpmmlqejpmeubfxsulyxbmpebplzbtclfzhblxexbmpezbhcbexehexpmfxsulyxmxeeulbzjlsgzxmelqegleelyfzmcllmfytseliepzmtpmlpoblklyzgixoolylmefxsulyelqegleelybilslmixmrpmxebspbxexpmxmeuljlbbzrl
Mu: 11, Sh: 14, M: vfscostmagtgnaieiwttsxlqwtlbimezbsfeitwliwsgiajsmgoiseleitwlgiojilelolewtmezbsfetellbsigqszngetlsxlnsllsfmgtjsstmfazlsplwgtawtswvisrsfgnpevvsfstlmezbsflsxlnsllsfipszstpetywtelizwielewtetlbsqsiigys
Mu: 11, Sh: 15, M: cmzjvzathnanuhplpdaazesxdasiptlgizmlpadspdznphqztnvpzlslpadsnpvqpslsvsldatlgizmlalssizpnxzgunlaszesuzsszmtnaqzzatmhgszwsdnahdazdcpzyzmnuwlcczmzastlgizmszesuzsszmpwzgzawlafdalspgdplsldalasizxzppnfz
Mu: 11, Sh: 16, M: jtgqcghaouhubowswkhhglzekhzpwasnpgtswhkzwkguwoxgaucwgszswhkzuwcxwzszczskhasnpgtshszzpgwuegnbushzglzbgzzgtauhxgghatonzgdzkuhokhgkjwgfgtubdsjjgtghzasnpgtzglzbgzzgtwdgnghdshmkhszwnkwszskhshzpgegwwumg
Mu: 11, Sh: 17, M: qanxjnohvbobivdzdroonsglrogwdhzuwnazdorgdrnbdvenhbjdnzgzdorgbdjedgzgjgzrohzuwnazozggwndblnuibzognsginggnahboennohavugnkgrbovronrqdnmnabikzqqnanoghzuwnagnsginggnadknunokzotrozgdurdzgzrozogwnlnddbtn
Mu: 11, Sh: 18, M: xhuequvocivipckgkyvvuznsyvndkogbduhgkvynkyuikcluoiqkugngkvynikqlkngnqngyvogbduhgvgnndukisubpigvnuznpunnuhoivluuvohcbnurnyivcyvuyxkutuhiprgxxuhuvnogbduhnuznpunnuhkrubuvrgvayvgnkbykgngyvgvndusukkiau
Mu: 11, Sh: 19, M: eoblxbcvjpcpwjrnrfccbguzfcukrvnikbonrcfurfbprjsbvpxrbnunrcfuprxsrunuxunfcvnikboncnuukbrpzbiwpncubguwbuubovpcsbbcvojiubyufpcjfcbferbabopwyneebobcuvnikboubguwbuuborybibcynchfcnurifrnunfcncukbzbrrphb
Mu: 11, Sh: 20, M: lviseijcqwjwdqyuymjjinbgmjbrycuprivuyjmbymiwyqzicweyiubuyjmbwyezybubebumjcuprivujubbriywgipdwujbinbdibbivcwjziijcvqpbifbmwjqmjimlyihivwdfullivijbcuprivbinbdibbivyfipijfujomjubypmyubumjujbrigiyywoi
Mu: 11, Sh: 21, M: scpzlpqjxdqdkxfbftqqpuintqiyfjbwypcbfqtiftpdfxgpjdlfpbibfqtidflgfibilibtqjbwypcbqbiiypfdnpwkdbqipuikpiipcjdqgppqjcxwipmitdqxtqptsfpopcdkmbsspcpqijbwypcipuikpiipcfmpwpqmbqvtqbifwtfbibtqbqiypnpffdvp
Mu: 11, Sh: 22, M: zjwgswxqekxkremimaxxwbpuaxpfmqidfwjimxapmawkmenwqksmwipimxapkmsnmpipspiaxqidfwjixippfwmkuwdrkixpwbprwppwjqkxnwwxqjedpwtpakxeaxwazmwvwjkrtizzwjwxpqidfwjpwbprwppwjmtwdwxtixcaxipmdamipiaxixpfwuwmmkcw
Mu: 11, Sh: 23, M: gqdnzdexlreryltptheediwbhewmtxpkmdqptehwthdrtludxrztdpwptehwrtzutwpwzwphexpkmdqpepwwmdtrbdkyrpewdiwydwwdqxreuddexqlkwdawhrelhedhgtdcdqryapggdqdewxpkmdqwdiwydwwdqtadkdeapejhepwtkhtpwphepewmdbdttrjd
Mu: 11, Sh: 24, M: nxkugklesylyfsawaollkpdioldtaewrtkxwalodaokyasbkeygakwdwalodyagbadwdgdwolewrtkxwlwddtkayikrfywldkpdfkddkxeylbkklexsrdkhdoylsolkonakjkxyfhwnnkxkldewrtkxdkpdfkddkxahkrklhwlqolwdaroawdwolwldtkikaayqk
Mu: 11, Sh: 25, M: uerbnrslzfsfmzhdhvssrwkpvskahldyaredhsvkhvrfhzirlfnhrdkdhsvkfhnihkdknkdvsldyaredsdkkarhfprymfdskrwkmrkkrelfsirrslezykrokvfszvsrvuhrqrefmoduurerskldyarekrwkmrkkrehoryrsodsxvsdkhyvhdkdvsdskarprhhfxr
Mu: 15, Sh: 0, M: zpcsgcbiuobohumqmybbcxjeybjtmiqvtcpqmbyjmycomulciogmcqjqmbyjomglmjqjgjqybiqvtcpqbqjjtcmoecvhoqbjcxjhcjjcpioblccbipuvjcfjyobuybcyzmcdcpohfqzzcpcbjiqvtcpjcxjhcjjcpmfcvcbfqbwybqjmvymqjqybqbjtcecmmowc
Mu: 15, Sh: 1, M: sivlzvubnhuhanfjfruuvqcxrucmfbjomvijfurcfrvhfnevbhzfvjcjfurchfzefcjczcjrubjomvijujccmvfhxvoahjucvqcavccvibhuevvubinocvycrhunruvrsfvwvihayjssvivucbjomvicvqcavccvifyvovuyjuprujcforfjcjrujucmvxvffhpv
Mu: 15, Sh: 2, M: lboesonuganatgycyknnojvqknvfyuchfobcynkvykoaygxouasyocvcynkvaysxyvcvsvcknuchfobcncvvfoyaqohtacnvojvtovvobuanxoonubghvorvkangknoklyopobatrcllobonvuchfobvojvtovvobyrohonrcnikncvyhkycvckncnvfoqoyyaio
Mu: 15, Sh: 3, M: euhxlhgnztgtmzrvrdgghcojdgoyrnvayhuvrgdordhtrzqhntlrhvovrgdotrlqrovolovdgnvayhuvgvooyhrtjhamtvgohcomhoohuntgqhhgnuzaohkodtgzdghderhihutmkveehuhgonvayhuohcomhoohurkhahgkvgbdgvoradrvovdgvgoyhjhrrtbh
Mu: 15, Sh: 4, M: xnaqeazgsmzmfskokwzzavhcwzhrkgotranokzwhkwamksjagmekaohokzwhmkejkhohehowzgotranozohhrakmcatfmozhavhfahhangmzjaazgnsthadhwmzswzawxkabanmfdoxxanazhgotranhavhfahhankdatazdozuwzohktwkohowzozhracakkmua
Mu: 15, Sh: 5, M: qgtjxtszlfsfyldhdpsstoavpsakdzhmktghdspadptfdlctzfxdthahdspafdxcdahaxahpszhmktghshaaktdfvtmyfhsatoaytaatgzfscttszglmatwapfslpstpqdtutgfywhqqtgtsazhmktgatoaytaatgdwtmtswhsnpshadmpdhahpshsaktvtddfnt
Mu: 15, Sh: 6, M: jzmcqmlseylyrewawillmhtoiltdwsafdmzawlitwimywevmsyqwmatawlitywqvwtatqtailsafdmzalattdmwyomfryaltmhtrmttmzsylvmmlszeftmptiyleilmijwmnmzyrpajjmzmltsafdmztmhtrmttmzwpmfmlpalgilatwfiwatailaltdmomwwygm
Mu: 15, Sh: 7, M: csfvjfelxrerkxptpbeefamhbemwpltywfstpebmpbfrpxoflrjpftmtpebmrpjopmtmjmtbeltywfstetmmwfprhfykrtemfamkfmmfslreoffelsxymfimbrexbefbcpfgfsrkitccfsfemltywfsmfamkfmmfspifyfeitezbetmpybptmtbetemwfhfpprzf
Mu: 15, Sh: 8, M: vlyocyxeqkxkdqimiuxxytfauxfpiemrpylmixufiuykiqhyekciymfmixufkichifmfcfmuxemrpylmxmffpyikayrdkmxfytfdyffylekxhyyxelqrfybfukxquxyuviyzylkdbmvvylyxfemrpylfytfdyffylibyryxbmxsuxmfiruimfmuxmxfpyayiiksy
Mu: 15, Sh: 9, M: oerhvrqxjdqdwjbfbnqqrmytnqyibxfkirefbqnybnrdbjarxdvbrfyfbqnydbvabyfyvyfnqxfkirefqfyyirbdtrkwdfqyrmywryyrexdqarrqxejkyruyndqjnqrnobrsredwufoorerqyxfkireyrmywryyreburkrqufqlnqfybknbfyfnqfqyirtrbbdlr
Mu: 15, Sh: 10, M: hxkaokjqcwjwpcuyugjjkfrmgjrbuqydbkxyujgrugkwuctkqwoukyryujgrwuoturyrorygjqydbkxyjyrrbkuwmkdpwyjrkfrpkrrkxqwjtkkjqxcdrknrgwjcgjkghuklkxwpnyhhkxkjrqydbkxrkfrpkrrkxunkdkjnyjegjyrudguyrygjyjrbkmkuuwek
Mu: 15, Sh: 11, M: aqdthdcjvpcpivnrnzccdykfzckunjrwudqrnczknzdpnvmdjphndrkrnczkpnhmnkrkhkrzcjrwudqrcrkkudnpfdwiprckdykidkkdqjpcmddcjqvwkdgkzpcvzcdzandedqpigraadqdckjrwudqkdykidkkdqngdwdcgrcxzcrknwznrkrzcrckudfdnnpxd
Mu: 15, Sh: 12, M: tjwmawvcoivibogkgsvvwrdysvdngckpnwjkgvsdgswigofwciagwkdkgvsdigafgdkdadksvckpnwjkvkddnwgiywpbikvdwrdbwddwjcivfwwvcjopdwzdsivosvwstgwxwjibzkttwjwvdckpnwjdwrdbwddwjgzwpwvzkvqsvkdgpsgkdksvkvdnwywggiqw
Mu: 15, Sh: 13, M: mcpftpovhbobuhzdzloopkwrlowgzvdigpcdzolwzlpbzhypvbtzpdwdzolwbztyzwdwtwdlovdigpcdodwwgpzbrpiubdowpkwupwwpcvboyppovchiwpswlbohloplmzpqpcbusdmmpcpowvdigpcwpkwupwwpczspiposdojlodwzilzdwdlodowgprpzzbjp
Mu: 15, Sh: 14, M: fviymihoauhunaswsehhidpkehpzsowbzivwshepseiusarioumsiwpwshepusmrspwpmpwehowbzivwhwppzisukibnuwhpidpnippivouhriihovabpilpeuhaehiefsijivunlwffivihpowbzivpidpnippivslibihlwhcehwpsbeswpwehwhpzikissuci
Mu: 15, Sh: 15, M: yobrfbahtnangtlplxaabwidxaislhpusboplaxilxbnltkbhnflbpiplaxinlfklipifipxahpusbopapiisblndbugnpaibwigbiibohnakbbahotuibeixnatxabxylbcbongepyybobaihpusboibwigbiibolebubaepavxapiluxlpipxapaisbdbllnvb
Mu: 15, Sh: 16, M: rhukyutamgtgzmeieqttupbwqtbleainluhietqbequgemduagyeuibietqbgeydebibybiqtainluhitibbluegwunzgitbupbzubbuhagtduutahmnbuxbqgtmqtuqreuvuhgzxirruhutbainluhbupbzubbuhexunutxitoqtibenqeibiqtitbluwueegou
Mu: 15, Sh: 17, M: kandrnmtfzmzsfxbxjmmniupjmuextbgenabxmjuxjnzxfwntzrxnbubxmjuzxrwxuburubjmtbgenabmbuuenxzpngszbmuniusnuunatzmwnnmtafgunqujzmfjmnjkxnonazsqbkknanmutbgenauniusnuunaxqngnmqbmhjmbuxgjxbubjmbmuenpnxxzhn
Mu: 15, Sh: 18, M: dtgwkgfmysfslyquqcffgbnicfnxqmuzxgtuqfcnqcgsqypgmskqgunuqfcnsqkpqnunknucfmuzxgtufunnxgqsigzlsufngbnlgnngtmsfpggfmtyzngjncsfycfgcdqghgtsljuddgtgfnmuzxgtngbnlgnngtqjgzgfjufacfunqzcqunucfufnxgigqqsag
Mu: 15, Sh: 19, M: wmzpdzyfrlylerjnjvyyzugbvygqjfnsqzmnjyvgjvzljrizfldjzngnjyvgljdijgngdgnvyfnsqzmnynggqzjlbzselnygzugezggzmflyizzyfmrsgzcgvlyrvyzvwjzazmlecnwwzmzygfnsqzmgzugezggzmjczszycnytvyngjsvjngnvynygqzbzjjltz
Mu: 15, Sh: 20, M: pfsiwsrykerexkcgcorrsnzuorzjcygljsfgcrozcoseckbsyewcsgzgcrozecwbczgzwzgorygljsfgrgzzjsceuslxegrzsnzxszzsfyerbssryfklzsvzoerkorsopcstsfexvgppsfsrzygljsfzsnzxszzsfcvslsrvgrmorgzclocgzgorgrzjsusccems
Mu: 15, Sh: 21, M: iylbplkrdxkxqdvzvhkklgsnhkscvrzeclyzvkhsvhlxvdulrxpvlzszvkhsxvpuvszspszhkrzeclyzkzssclvxnleqxzkslgsqlsslyrxkullkrydesloshxkdhklhivlmlyxqoziilylksrzeclyslgsqlsslyvolelkozkfhkzsvehvzszhkzksclnlvvxfl
Mu: 15, Sh: 22, M: breuiedkwqdqjwosoaddezlgadlvoksxversodaloaeqownekqioeslsodalqoinolslilsadksxversdsllveoqgexjqsdlezljellerkqdneedkrwxlehlaqdwadeaboeferqjhsbberedlksxverlezljellerohexedhsdyadsloxaoslsadsdlvegeooqye
Mu: 15, Sh: 23, M: ukxnbxwdpjwjcphlhtwwxseztweohdlqoxklhwtehtxjhpgxdjbhxlelhwtejhbghelebeltwdlqoxklwleeoxhjzxqcjlwexsecxeexkdjwgxxwdkpqexaetjwptwxtuhxyxkjcaluuxkxwedlqoxkexsecxeexkhaxqxwalwrtwlehqthleltwlweoxzxhhjrx
Mu: 15, Sh: 24, M: ndqguqpwicpcviaeamppqlxsmpxhawejhqdeapmxamqcaizqwcuaqexeapmxcauzaxexuxempwejhqdepexxhqacsqjvcepxqlxvqxxqdwcpzqqpwdijxqtxmcpimpqmnaqrqdcvtennqdqpxwejhqdxqlxvqxxqdatqjqptepkmpexajmaexempepxhqsqaackq
Mu: 15, Sh: 25, M: gwjznjipbvivobtxtfiijeqlfiqatpxcajwxtifqtfjvtbsjpvntjxqxtifqvtnstqxqnqxfipxcajwxixqqajtvljcovxiqjeqojqqjwpvisjjipwbcqjmqfvibfijfgtjkjwvomxggjwjiqpxcajwqjeqojqqjwtmjcjimxidfixqtcftxqxfixiqajljttvdj
Mu: 17, Sh: 0, M: tbowqohekuhuxkgigmhhoflcmhldgeirdobighmlgmougkzoeuqgoilighmlugqzglilqlimheirdobihilldogucorxuihloflxollobeuhzoohebkrlojlmuhkmhomtgovobuxjittobohleirdobloflxollobgjorohjihymhilgrmgilimhihldocogguyo
Mu: 17, Sh: 1, M: werztrkhnxkxanjljpkkriofpkogjhlugreljkpojprxjncrhxtjrloljkpoxjtcjolotolpkhlugrelkloogrjxfruaxlkorioaroorehxkcrrkhenuormopxknpkrpwjryrexamlwwrerkohlugreorioaroorejmrurkmlkbpklojupjlolpklkogrfrjjxbr
Mu: 17, Sh: 2, M: zhucwunkqanadqmomsnnulrisnrjmkoxjuhomnsrmsuamqfukawmuoromnsramwfmrorwrosnkoxjuhonorrjumaiuxdaonrulrdurruhkanfuunkhqxruprsanqsnuszmubuhadpozzuhunrkoxjuhrulrdurruhmpuxunponesnormxsmorosnonrjuiummaeu
Mu: 17, Sh: 3, M: ckxfzxqntdqdgtprpvqqxoulvqumpnramxkrpqvupvxdptixndzpxrurpqvudpzipuruzurvqnramxkrqruumxpdlxagdrquxougxuuxkndqixxqnktauxsuvdqtvqxvcpxexkdgsrccxkxqunramxkuxougxuuxkpsxaxqsrqhvqrupavprurvqrqumxlxppdhx
Mu: 17, Sh: 4, M: fnaicatqwgtgjwsusyttarxoytxpsqudpanustyxsyagswlaqgcsauxustyxgsclsxuxcxuytqudpanutuxxpasgoadjgutxarxjaxxanqgtlaatqnwdxavxygtwytayfsahangjvuffanatxqudpanxarxjaxxansvadatvutkytuxsdysuxuytutxpaoassgka
Mu: 17, Sh: 5, M: iqdlfdwtzjwjmzvxvbwwduarbwasvtxgsdqxvwbavbdjvzodtjfvdxaxvwbajvfovaxafaxbwtxgsdqxwxaasdvjrdgmjxwaduamdaadqtjwoddwtqzgadyabjwzbwdbivdkdqjmyxiidqdwatxgsdqaduamdaadqvydgdwyxwnbwxavgbvxaxbwxwasdrdvvjnd
Mu: 17, Sh: 6, M: ltgoigzwcmzmpcyayezzgxduezdvywajvgtayzedyegmycrgwmiygadayzedmyirydadidaezwajvgtazaddvgymugjpmazdgxdpgddgtwmzrggzwtcjdgbdemzcezgelygngtmpballgtgzdwajvgtdgxdpgddgtybgjgzbazqezadyjeyadaezazdvgugyymqg
Mu: 17, Sh: 7, M: owjrljczfpcpsfbdbhccjagxhcgybzdmyjwdbchgbhjpbfujzplbjdgdbchgpblubgdglgdhczdmyjwdcdggyjbpxjmspdcgjagsjggjwzpcujjczwfmgjeghpcfhcjhobjqjwpsedoojwjcgzdmyjwgjagsjggjwbejmjcedcthcdgbmhbdgdhcdcgyjxjbbptj
Mu: 17, Sh: 8, M: rzmuomfcisfsviegekffmdjakfjbecgpbmzgefkjekmseixmcsoemgjgefkjseoxejgjojgkfcgpbmzgfgjjbmesampvsgfjmdjvmjjmzcsfxmmfczipjmhjksfikfmkremtmzsvhgrrmzmfjcgpbmzjmdjvmjjmzehmpmfhgfwkfgjepkegjgkfgfjbmameeswm
Mu: 17, Sh: 9, M: ucpxrpiflvivylhjhniipgmdnimehfjsepcjhinmhnpvhlapfvrhpjmjhinmvhrahmjmrmjnifjsepcjijmmephvdpsyvjimpgmypmmpcfviappifclsmpkmnvilnipnuhpwpcvykjuupcpimfjsepcmpgmypmmpchkpspikjiznijmhsnhjmjnijimepdphhvzp
Mu: 17, Sh: 10, M: xfsauslioylybokmkqllsjpgqlphkimvhsfmklqpkqsykodsiyuksmpmklqpykudkpmpupmqlimvhsfmlmpphskygsvbymlpsjpbsppsfiyldsslifovpsnpqyloqlsqxkszsfybnmxxsfslpimvhsfpsjpbsppsfknsvslnmlcqlmpkvqkmpmqlmlphsgskkycs
Mu: 17, Sh: 11, M: aivdxvolrbobernpntoovmsjtosknlpykvipnotsntvbnrgvlbxnvpspnotsbnxgnspsxsptolpykvipopsskvnbjvyebposvmsevssvilbogvvolirysvqstbortovtanvcvibeqpaavivoslpykvisvmsevssvinqvyvoqpoftopsnytnpsptoposkvjvnnbfv
Mu: 17, Sh: 12, M: dlygayrouerehuqsqwrrypvmwrvnqosbnylsqrwvqwyequjyoeaqysvsqrwveqajqvsvavswrosbnylsrsvvnyqemybhesrvypvhyvvyloerjyyrolubvytvweruwrywdqyfylehtsddylyrvosbnylvypvhyvvylqtybyrtsriwrsvqbwqsvswrsrvnymyqqeiy
Mu: 17, Sh: 13, M: gobjdburxhuhkxtvtzuubsypzuyqtrveqbovtuzytzbhtxmbrhdtbvyvtuzyhtdmtyvydyvzurveqbovuvyyqbthpbekhvuybsykbyyborhumbburoxeybwyzhuxzubzgtbibohkwvggbobuyrveqboybsykbyybotwbebuwvulzuvyteztvyvzuvuyqbpbtthlb
Mu: 17, Sh: 14, M: jremgexuakxknawywcxxevbscxbtwuyhterywxcbwcekwapeukgweybywxcbkwgpwbybgbycxuyhteryxybbtewksehnkyxbevbnebberukxpeexurahbezbckxacxecjwelerknzyjjerexbuyhterbevbnebberwzehexzyxocxybwhcwybycxyxbtesewwkoe
Mu: 17, Sh: 15, M: muhpjhaxdnanqdzbzfaahyevfaewzxbkwhubzafezfhnzdshxnjzhbebzafenzjszebejebfaxbkwhubabeewhznvhkqnbaehyeqheehuxnashhaxudkehcefnadfahfmzhohunqcbmmhuhaexbkwhuehyeqheehuzchkhacbarfabezkfzbebfabaewhvhzznrh
Mu: 17, Sh: 16, M: pxksmkdagqdqtgceciddkbhyidhzcaenzkxecdihcikqcgvkaqmckehecdihqcmvchehmheidaenzkxedehhzkcqykntqedhkbhtkhhkxaqdvkkdaxgnhkfhiqdgidkipckrkxqtfeppkxkdhaenzkxhkbhtkhhkxcfknkdfeduidehcniceheidedhzkykccquk
Mu: 17, Sh: 17, M: sanvpngdjtgtwjfhflggnekblgkcfdhqcnahfglkflntfjyndtpfnhkhfglktfpyfkhkpkhlgdhqcnahghkkcnftbnqwthgknekwnkknadtgynngdajqknikltgjlgnlsfnunatwihssnangkdhqcnaknekwnkknafinqngihgxlghkfqlfhkhlghgkcnbnfftxn
Mu: 17, Sh: 18, M: vdqysqjgmwjwzmikiojjqhneojnfigktfqdkijonioqwimbqgwsiqknkijonwisbinknsnkojgktfqdkjknnfqiweqtzwkjnqhnzqnnqdgwjbqqjgdmtnqlnowjmojqoviqxqdwzlkvvqdqjngktfqdnqhnzqnnqdilqtqjlkjaojknitoiknkojkjnfqeqiiwaq
Mu: 17, Sh: 19, M: ygtbvtmjpzmzcplnlrmmtkqhrmqiljnwitgnlmrqlrtzlpetjzvltnqnlmrqzlvelqnqvqnrmjnwitgnmnqqitlzhtwcznmqtkqctqqtgjzmettmjgpwqtoqrzmprmtryltatgzconyytgtmqjnwitgqtkqctqqtglotwtmonmdrmnqlwrlnqnrmnmqithtllzdt
Mu: 17, Sh: 20, M: bjweywpmscpcfsoqouppwntkuptlomqzlwjqoputouwcoshwmcyowqtqoputcoyhotqtytqupmqzlwjqpqttlwockwzfcqptwntfwttwjmcphwwpmjsztwrtucpsupwubowdwjcfrqbbwjwptmqzlwjtwntfwttwjorwzwprqpgupqtozuoqtqupqptlwkwoocgw
Mu: 17, Sh: 21, M: emzhbzspvfsfivrtrxsszqwnxsworptcozmtrsxwrxzfrvkzpfbrztwtrsxwfrbkrwtwbwtxsptcozmtstwwozrfnzciftswzqwizwwzmpfskzzspmvcwzuwxfsvxszxerzgzmfiuteezmzswptcozmwzqwizwwzmruzczsutsjxstwrcxrtwtxstswoznzrrfjz
Mu: 17, Sh: 22, M: hpckecvsyivilyuwuavvctzqavzruswfrcpwuvazuaciuyncsieucwzwuvaziuenuzwzezwavswfrcpwvwzzrcuiqcfliwvzctzlczzcpsivnccvspyfzcxzaivyavcahucjcpilxwhhcpcvzswfrcpzctzlczzcpuxcfcvxwvmavwzufauwzwavwvzrcqcuuimc
Mu: 17, Sh: 23, M: ksfnhfyvblylobxzxdyyfwctdycuxvziufszxydcxdflxbqfvlhxfzczxydclxhqxczchczdyvziufszyzccufxltfiolzycfwcofccfsvlyqffyvsbicfacdlybdyfdkxfmfsloazkkfsfycvziufscfwcofccfsxafifyazypdyzcxidxzczdyzycuftfxxlpf
Mu: 17, Sh: 24, M: nviqkibyeoboreacagbbizfwgbfxayclxivcabgfagioaetiyokaicfcabgfoaktafcfkfcgbyclxivcbcffxiaowilrocbfizfriffivyobtiibyvelfidfgobegbignaipivordcnnivibfyclxivfizfriffivadilibdcbsgbcfalgacfcgbcbfxiwiaaosi
Mu: 17, Sh: 25, M: qyltnlebhreruhdfdjeelcizjeiadbfoalyfdejidjlrdhwlbrndlfifdejirdnwdifinifjebfoalyfefiialdrzlourfeilciuliilybrewllebyhoilgijrehjeljqdlslyrugfqqlyleibfoalyilciuliilydglolegfevjefidojdfifjefeialzlddrvl
Mu: 19, Sh: 0, M: rfsgcsjuywjwlyeoeijjszdkijdpeuohpsfoejideisweyvsuwcesodoejidwecvedodcdoijuohpsfojoddpsewkshlwojdszdlsddsfuwjvssjufyhdstdiwjyijsiresbsfwltorrsfsjduohpsfdszdlsddsfetshsjtojqijodehieodoijojdpskseewqs
Mu: 19, Sh: 1, M: guhvrhyjnlylantdtxyyhoszxysetjdwehudtyxstxhltnkhjlrthdsdtyxsltrktsdsrsdxyjdwehudydssehtlzhwaldyshosahsshujlykhhyjunwshisxlynxyhxgthqhulaidgghuhysjdwehushosahsshutihwhyidyfxydstwxtdsdxydysehzhttlfh
Mu: 19, Sh: 2, M: vjwkgwnycanapcisimnnwdhomnhtiysltwjsinmhimwaiczwyagiwshsinmhaigzihshghsmnysltwjsnshhtwiaowlpasnhwdhpwhhwjyanzwwnyjclhwxhmancmnwmviwfwjapxsvvwjwnhysltwjhwdhpwhhwjixwlwnxsnumnshilmishsmnsnhtwowiiauw
Mu: 19, Sh: 3, M: kylzvlcnrpcperxhxbcclswdbcwixnhailyhxcbwxblpxrolnpvxlhwhxcbwpxvoxwhwvwhbcnhailyhchwwilxpdlaephcwlswelwwlynpcollcnyrawlmwbpcrbclbkxlulypemhkklylcwnhailywlswelwwlyxmlalcmhcjbchwxabxhwhbchcwildlxxpjl
Mu: 19, Sh: 4, M: znaokarcgeretgmwmqrrahlsqrlxmcwpxanwmrqlmqaemgdacekmawlwmrqlemkdmlwlklwqrcwpxanwrwllxamesaptewrlahltallancerdaarcngplablqergqraqzmajanetbwzzanarlcwpxanlahltallanmbaparbwryqrwlmpqmwlwqrwrlxasammeya
Mu: 19, Sh: 5, M: ocpdzpgrvtgtivblbfggpwahfgambrlempclbgfabfptbvsprtzbplalbgfatbzsbalazalfgrlempclglaampbthpeitlgapwaipaapcrtgsppgrcveapqaftgvfgpfobpypctiqloopcpgarlempcapwaipaapcbqpepgqlgnfglabefblalfglgamphpbbtnp
Mu: 19, Sh: 6, M: dresoevgkivixkqaquvvelpwuvpbqgatberaqvupqueiqkhegioqeapaqvupiqohqpapopauvgatberavappbeqiwetxiavpelpxeppergivheevgrktpefpuivkuveudqenerixfadderevpgatberpelpxepperqfetevfavcuvapqtuqapauvavpbeweqqice
Mu: 19, Sh: 7, M: sgthdtkvzxkxmzfpfjkktaeljkeqfvpiqtgpfkjefjtxfzwtvxdftpepfkjexfdwfepedepjkvpiqtgpkpeeqtfxltimxpketaemteetgvxkwttkvgzietuejxkzjktjsftctgxmupsstgtkevpiqtgetaemteetgfutitkupkrjkpefijfpepjkpkeqtltffxrt
Mu: 19, Sh: 8, M: hviwsizkomzmboueuyzziptayztfukexfiveuzytuyimuolikmsuieteuzytmuslutetsteyzkexfivezettfiumaixbmeztiptbittivkmzliizkvoxtijtymzoyziyhuirivmbjehhiviztkexfivtiptbittivujixizjezgyzetuxyueteyzeztfiaiuumgi
Mu: 19, Sh: 9, M: wkxlhxozdbobqdjtjnooxeipnoiujztmuxktjonijnxbjdaxzbhjxtitjonibjhajitihitnoztmuxktotiiuxjbpxmqbtoixeiqxiixkzboaxxozkdmixyinbodnoxnwjxgxkbqytwwxkxoiztmuxkixeiqxiixkjyxmxoytovnotijmnjtitnotoiuxpxjjbvx
Mu: 19, Sh: 10, M: lzmawmdosqdqfsyiycddmtxecdxjyoibjmziydcxycmqyspmoqwymixiydcxqywpyxixwxicdoibjmzidixxjmyqembfqidxmtxfmxxmzoqdpmmdozsbxmnxcqdscdmclymvmzqfnillmzmdxoibjmzxmtxfmxxmzynmbmdnidkcdixybcyixicdidxjmemyyqkm
Mu: 19, Sh: 11, M: aobplbsdhfsfuhnxnrssbimtrsmyndxqyboxnsrmnrbfnhebdflnbxmxnsrmfnlenmxmlmxrsdxqyboxsxmmybnftbqufxsmbimubmmbodfsebbsdohqmbcmrfshrsbranbkbofucxaabobsmdxqybombimubmmboncbqbscxszrsxmnqrnxmxrsxsmybtbnnfzb
Mu: 19, Sh: 12, M: pdqeaqhswuhujwcmcghhqxbighbncsmfnqdmchgbcgqucwtqsuacqmbmchgbucatcbmbabmghsmfnqdmhmbbnqcuiqfjumhbqxbjqbbqdsuhtqqhsdwfbqrbguhwghqgpcqzqdujrmppqdqhbsmfnqdbqxbjqbbqdcrqfqhrmhoghmbcfgcmbmghmhbnqiqccuoq
Mu: 19, Sh: 13, M: esftpfwhljwjylrbrvwwfmqxvwqcrhbucfsbrwvqrvfjrlifhjprfbqbrwvqjrpirqbqpqbvwhbucfsbwbqqcfrjxfuyjbwqfmqyfqqfshjwiffwhsluqfgqvjwlvwfverfofsjygbeefsfwqhbucfsqfmqyfqqfsrgfufwgbwdvwbqruvrbqbvwbwqcfxfrrjdf
Mu: 19, Sh: 14, M: thuieulwaylynagqgkllubfmklfrgwqjruhqglkfgkuygaxuwyeguqfqglkfygexgfqfefqklwqjruhqlqffrugymujnyqlfubfnuffuhwylxuulwhajfuvfkylakluktguduhynvqttuhulfwqjruhfubfnuffuhgvujulvqlsklqfgjkgqfqklqlfrumuggysu
Mu: 19, Sh: 15, M: iwjxtjalpnancpvfvzaajqubzaugvlfygjwfvazuvzjnvpmjlntvjfufvazunvtmvufutufzalfygjwfafuugjvnbjycnfaujqucjuujwlnamjjalwpyujkuznapzajzivjsjwnckfiijwjaulfygjwujqucjuujwvkjyjakfahzafuvyzvfufzafaugjbjvvnhj
Mu: 19, Sh: 16, M: xlymiypaecpcrekukoppyfjqopjvkaunvylukpojkoyckebyacikyujukpojckibkjujijuopaunvylupujjvykcqynrcupjyfjryjjylacpbyypalenjyzjocpeopyoxkyhylcrzuxxylypjaunvyljyfjryjjylkzynypzupwopujknokujuopupjvyqykkcwy
Mu: 19, Sh: 17, M: manbxneptrergtzjzdeenuyfdeykzpjcknajzedyzdnrztqnprxznjyjzedyrzxqzyjyxyjdepjcknajejyyknzrfncgrjeynuygnyynapreqnnepatcynoydretdendmznwnargojmmnaneypjcknaynuygnyynazoncneojeldejyzcdzjyjdejeyknfnzzrln
Mu: 19, Sh: 18, M: bpcqmcteigtgvioyosttcjnustnzoeyrzcpyotsnoscgoifcegmocynyotsngomfonynmnysteyrzcpytynnzcogucrvgytncjnvcnncpegtfcctepirncdnsgtistcsboclcpgvdybbcpctneyrzcpncjnvcnncpodcrctdytastynorsoynystytnzcucoogac
Mu: 19, Sh: 19, M: qerfbritxvivkxdndhiirycjhicodtngorendihcdhrvdxurtvbdrncndihcvdbudcncbcnhitngoreninccordvjrgkvnicryckrccretviurritexgcrschvixhirhqdrarevksnqqrerictngorecryckrccredsrgrisniphincdghdncnhinicorjrddvpr
Mu: 19, Sh: 20, M: ftguqgximkxkzmscswxxgnrywxrdsicvdgtcsxwrswgksmjgikqsgcrcsxwrksqjsrcrqrcwxicvdgtcxcrrdgskygvzkcxrgnrzgrrgtikxjggxitmvrghrwkxmwxgwfsgpgtkzhcffgtgxricvdgtrgnrzgrrgtshgvgxhcxewxcrsvwscrcwxcxrdgygsskeg
Mu: 19, Sh: 21, M: uivjfvmxbzmzobhrhlmmvcgnlmgshxrksvirhmlghlvzhbyvxzfhvrgrhmlgzhfyhgrgfgrlmxrksvirmrggsvhznvkozrmgvcgovggvixzmyvvmxibkgvwglzmblmvluhvevizowruuvivmgxrksvigvcgovggvihwvkvmwrmtlmrghklhrgrlmrmgsvnvhhztv
Mu: 19, Sh: 22, M: jxkyukbmqobodqwgwabbkrvcabvhwmgzhkxgwbavwakowqnkmouwkgvgwbavowunwvgvuvgabmgzhkxgbgvvhkwockzdogbvkrvdkvvkxmobnkkbmxqzvklvaobqabkajwktkxodlgjjkxkbvmgzhkxvkrvdkvvkxwlkzkblgbiabgvwzawgvgabgbvhkckwwoik
Mu: 19, Sh: 23, M: ymznjzqbfdqdsflvlpqqzgkrpqkwlbvowzmvlqpklpzdlfczbdjlzvkvlqpkdljclkvkjkvpqbvowzmvqvkkwzldrzosdvqkzgkszkkzmbdqczzqbmfokzakpdqfpqzpylzizmdsavyyzmzqkbvowzmkzgkszkkzmlazozqavqxpqvkloplvkvpqvqkwzrzlldxz
Mu: 19, Sh: 24, M: nbocyofqusfshuakaeffovzgefzlaqkdlobkafezaeosauroqsyaokzkafezsayrazkzyzkefqkdlobkfkzzloasgodhskfzovzhozzobqsfroofqbudzopzesfuefoenaoxobshpknnobofzqkdlobzovzhozzobapodofpkfmefkzadeakzkefkfzlogoaasmo
Mu: 19, Sh: 25, M: cqdrndufjhuhwjpzptuudkovtuoapfzsadqzputoptdhpjgdfhnpdzozputohpngpozonoztufzsadqzuzooadphvdswhzuodkowdoodqfhugddufqjsodeothujtudtcpdmdqhwezccdqduofzsadqodkowdoodqpedsduezubtuzopstpzoztuzuoadvdpphbd
Mu: 21, Sh: 0, M: dhuyiuxcskxkfsqeqgxxujzogxzvqcepvuheqxgzqgukqstuckiquezeqxgzkqitqzezizegxcepvuhexezzvuqkoupfkexzujzfuzzuhckxtuuxchspzulzgkxsgxugdquruhkfledduhuxzcepvuhzujzfuzzuhqlupuxlexmgxezqpgqezegxexzvuouqqkmu
Mu: 21, Sh: 1, M: ycptdpsxnfsfanlzlbsspeujbsuqlxzkqpczlsbulbpflnopxfdlpzuzlsbufldoluzuduzbsxzkqpczszuuqplfjpkafzsupeuapuupcxfsoppsxcnkupgubfsnbspbylpmpcfagzyypcpsuxzkqpcupeuapuupclgpkpsgzshbszulkblzuzbszsuqpjpllfhp
Mu: 21, Sh: 2, M: txkoyknsianavigugwnnkzpewnplgsuflkxugnwpgwkagijksaygkupugnwpagyjgpupypuwnsuflkxunupplkgaekfvaunpkzpvkppkxsanjkknsxifpkbpwaniwnkwtgkhkxavbuttkxknpsuflkxpkzpvkppkxgbkfknbuncwnupgfwgupuwnunplkekggack
Mu: 21, Sh: 3, M: osfjtfindvivqdbpbriifukzrikgbnpagfspbirkbrfvbdefnvtbfpkpbirkvbtebkpktkprinpagfspipkkgfbvzfaqvpikfukqfkkfsnvieffinsdakfwkrvidrifrobfcfsvqwpoofsfiknpagfskfukqfkkfsbwfafiwpixripkbarbpkpripikgfzfbbvxf
Mu: 21, Sh: 4, M: jnaeoadiyqdqlywkwmddapfumdfbwikvbankwdmfwmaqwyzaiqowakfkwdmfqwozwfkfofkmdikvbankdkffbawquavlqkdfapflaffaniqdzaadinyvfarfmqdymdamjwaxanqlrkjjanadfikvbanfapflaffanwravadrkdsmdkfwvmwkfkmdkdfbauawwqsa
Mu: 21, Sh: 5, M: eivzjvydtlylgtrfrhyyvkaphyawrdfqwvifryharhvlrtuvdljrvfafryhalrjurafajafhydfqwvifyfaawvrlpvqglfyavkagvaavidlyuvvyditqavmahlythyvhervsvilgmfeevivyadfqwviavkagvaavirmvqvymfynhyfarqhrfafhyfyawvpvrrlnv
Mu: 21, Sh: 6, M: zdqueqtyogtgbomamcttqfvkctvrmyalrqdamtcvmcqgmopqygemqavamtcvgmepmvavevactyalrqdatavvrqmgkqlbgatvqfvbqvvqdygtpqqtydolvqhvcgtoctqczmqnqdgbhazzqdqtvyalrqdvqfvbqvvqdmhqlqthatictavmlcmavactatvrqkqmmgiq
Mu: 21, Sh: 7, M: uylpzlotjbobwjhvhxoolaqfxoqmhtvgmlyvhoxqhxlbhjkltbzhlvqvhoxqbhzkhqvqzqvxotvgmlyvovqqmlhbflgwbvoqlaqwlqqlytbokllotyjgqlcqxbojxolxuhlilybwcvuulyloqtvgmlyqlaqwlqqlyhclglocvodxovqhgxhvqvxovoqmlflhhbdl
Mu: 21, Sh: 8, M: ptgkugjoewjwrecqcsjjgvlasjlhcoqbhgtqcjslcsgwcefgowucgqlqcjslwcufclqlulqsjoqbhgtqjqllhgcwagbrwqjlgvlrgllgtowjfggjoteblgxlswjesjgspcgdgtwrxqppgtgjloqbhgtlgvlrgllgtcxgbgjxqjysjqlcbscqlqsjqjlhgagccwyg
Mu: 21, Sh: 9, M: kobfpbejzrermzxlxneebqgvnegcxjlwcbolxengxnbrxzabjrpxblglxengrxpaxglgpglnejlwcbolelggcbxrvbwmrlegbqgmbggbojreabbejozwgbsgnreznebnkxbybormslkkbobegjlwcbogbqgmbggboxsbwbesletnelgxwnxlglnelegcbvbxxrtb
Mu: 21, Sh: 10, M: fjwakwzeumzmhusgsizzwlbqizbxsegrxwjgszibsiwmsuvwemkswgbgszibmskvsbgbkbgizegrxwjgzgbbxwsmqwrhmgzbwlbhwbbwjemzvwwzejurbwnbimzuizwifswtwjmhngffwjwzbegrxwjbwlbhwbbwjsnwrwzngzoizgbsrisgbgizgzbxwqwssmow
Mu: 21, Sh: 11, M: aervfruzphuhcpnbnduurgwlduwsnzbmsrebnudwndrhnpqrzhfnrbwbnudwhnfqnwbwfwbduzbmsrebubwwsrnhlrmchbuwrgwcrwwrezhuqrruzepmwriwdhupdurdanrorehcibaareruwzbmsrewrgwcrwwrenirmruibujdubwnmdnbwbdubuwsrlrnnhjr
Mu: 21, Sh: 12, M: vzmqampukcpcxkiwiyppmbrgyprniuwhnmzwipyriymciklmucaimwrwipyrcialirwrarwypuwhnmzwpwrrnmicgmhxcwprmbrxmrrmzucplmmpuzkhrmdrycpkypmyvimjmzcxdwvvmzmpruwhnmzrmbrxmrrmzidmhmpdwpeypwrihyiwrwypwprnmgmiicem
Mu: 21, Sh: 13, M: quhlvhkpfxkxsfdrdtkkhwmbtkmidprcihurdktmdthxdfghpxvdhrmrdktmxdvgdmrmvmrtkprcihurkrmmihdxbhcsxrkmhwmshmmhupxkghhkpufcmhymtxkftkhtqdhehuxsyrqqhuhkmprcihumhwmshmmhudyhchkyrkztkrmdctdrmrtkrkmihbhddxzh
Mu: 21, Sh: 14, M: lpcgqcfkasfsnaymyoffcrhwofhdykmxdcpmyfohyocsyabcksqycmhmyfohsyqbyhmhqhmofkmxdcpmfmhhdcyswcxnsmfhcrhnchhcpksfbccfkpaxhcthosfaofcolyczcpsntmllcpcfhkmxdcphcrhnchhcpytcxcftmfuofmhyxoymhmofmfhdcwcyysuc
Mu: 21, Sh: 15, M: gkxblxafvnanivthtjaaxmcrjacytfhsyxkhtajctjxntvwxfnltxhchtajcntlwtchclchjafhsyxkhahccyxtnrxsinhacxmcixccxkfnawxxafkvscxocjnavjaxjgtxuxkniohggxkxacfhsyxkcxmcixccxktoxsxaohapjahctsjthchjahacyxrxttnpx
Mu: 21, Sh: 16, M: bfswgsvaqividqocoevvshxmevxtoacntsfcovexoesioqrsaigoscxcovexiogroxcxgxcevacntsfcvcxxtsoimsndicvxshxdsxxsfaivrssvafqnxsjxeivqevsebospsfidjcbbsfsvxacntsfxshxdsxxsfojsnsvjcvkevcxoneocxcevcvxtsmsooiks
Mu: 21, Sh: 17, M: wanrbnqvldqdyljxjzqqncshzqsojvxionaxjqzsjzndjlmnvdbjnxsxjqzsdjbmjsxsbsxzqvxionaxqxssonjdhniydxqsncsynssnavdqmnnqvalisneszdqlzqnzwjnknadyexwwnanqsvxionasncsynssnajeninqexqfzqxsjizjxsxzqxqsonhnjjdfn
Mu: 21, Sh: 18, M: rvimwilqgylytgeseullixnculnjeqsdjivseluneuiyeghiqyweisnselunyewhensnwnsulqsdjivslsnnjieycidtyslnixntinnivqylhiilqvgdniznuylguliureifivytzsrrivilnqsdjivnixntinnivezidilzslaulsneduesnsulslnjicieeyai
Mu: 21, Sh: 19, M: mqdhrdglbtgtobznzpggdsixpgiezlnyedqnzgpizpdtzbcdltrzdninzgpitzrczinirinpglnyedqngniiedztxdyotngidsiodiidqltgcddglqbyiduiptgbpgdpmzdadqtounmmdqdgilnyedqidsiodiidqzudydgungvpgnizypzninpgngiedxdzztvd
Mu: 21, Sh: 20, M: hlycmybgwobojwuiukbbyndskbdzugitzyliubkdukyouwxygomuyidiubkdoumxudidmdikbgitzylibiddzyuosytjoibdyndjyddylgobxyybglwtdypdkobwkbykhuyvylojpihhylybdgitzyldyndjyddylupytybpibqkbidutkuidikbibdzysyuuoqy
Mu: 21, Sh: 21, M: cgtxhtwbrjwjerpdpfwwtiynfwyupbdoutgdpwfypftjprstbjhptdydpwfyjphspydyhydfwbdoutgdwdyyutpjntoejdwytiyetyytgbjwsttwbgroytkyfjwrfwtfcptqtgjekdcctgtwybdoutgytiyetyytgpktotwkdwlfwdypofpdydfwdwyutntppjlt
Mu: 21, Sh: 22, M: xboscorwmerezmkykarrodtiartpkwyjpobykratkaoekmnoweckoytykratekcnktytctyarwyjpobyryttpokeiojzeyrtodtzottobwernoorwbmjtoftaermaroaxkolobezfyxxobortwyjpobtodtzottobkfojorfyrgarytkjakytyaryrtpoiokkego
Mu: 21, Sh: 23, M: swjnxjmrhzmzuhftfvmmjyodvmokfrtekjwtfmvofvjzfhijrzxfjtotfmvozfxifotoxotvmrtekjwtmtookjfzdjeuztmojyoujoojwrzmijjmrwheojaovzmhvmjvsfjgjwzuatssjwjmortekjwojyoujoojwfajejmatmbvmtofevftotvmtmokjdjffzbj
Mu: 21, Sh: 24, M: nreisehmcuhupcaoaqhhetjyqhjfamozferoahqjaqeuacdemusaeojoahqjuasdajojsjoqhmozferohojjfeauyezpuohjetjpejjermuhdeehmrczjevjquhcqheqnaeberupvonnerehjmozferjetjpejjeravezehvohwqhojazqaojoqhohjfeyeaauwe
Mu: 21, Sh: 25, M: imzdnzchxpcpkxvjvlcczoetlceavhjuazmjvclevlzpvxyzhpnvzjejvclepvnyvejenejlchjuazmjcjeeazvptzukpjcezoekzeezmhpcyzzchmxuezqelpcxlczlivzwzmpkqjiizmzcehjuazmezoekzeezmvqzuzcqjcrlcjevulvjejlcjceaztzvvprz
Mu: 23, Sh: 0, M: fdqowqvmeiviresyskvvqphgkvhjsmyzjqdysvkhskqisexqmiwsqyhysvkhiswxshyhwhykvmyzjqdyvyhhjqsigqzriyvhqphrqhhqdmivxqqvmdezhqbhkivekvqkfsqlqdirbyffqdqvhmyzjqdhqphrqhhqdsbqzqvbyvukvyhszksyhykvyvhjqgqssiuq
Mu: 23, Sh: 1, M: omzxfzevnreranbhbteezyqpteqsbvhiszmhbetqbtzrbngzvrfbzhqhbetqrbfgbqhqfqhtevhiszmhehqqszbrpziarheqzyqazqqzmvregzzevmniqzkqtrenteztobzuzmrakhoozmzeqvhiszmqzyqazqqzmbkzizekhedtehqbitbhqhteheqszpzbbrdz
Mu: 23, Sh: 2, M: xvigoinewanajwkqkcnnihzycnzbkeqrbivqknczkciakwpieaokiqzqknczakopkzqzozqcneqrbivqnqzzbikayirjaqnzihzjizziveanpiinevwrzitzcanwcnicxkidivajtqxxivinzeqrbivzihzjizzivktirintqnmcnqzkrckqzqcnqnzbiyikkami
Mu: 23, Sh: 3, M: gerpxrwnfjwjsftztlwwrqihlwiktnzakreztwlitlrjtfyrnjxtrziztwlijtxytizixizlwnzakrezwziikrtjhrasjzwirqisriirenjwyrrwnefairciljwflwrlgtrmrejsczggrerwinzakreirqisriiretcrarwczwvlwzitaltzizlwzwikrhrttjvr
Mu: 23, Sh: 4, M: pnaygafwosfsbocicuffazrqufrtcwijtanicfurcuascohawsgcairicfurscghcrirgriufwijtanifirrtacsqajbsifrazrbarranwsfhaafwnojralrusfoufaupcavansblippanafrwijtanrazrbarranclajaflifeufircjuciriufifrtaqaccsea
Mu: 23, Sh: 5, M: ywjhpjofxbobkxlrldoojiazdoaclfrscjwrlodaldjblxqjfbpljrarlodablpqlarapardofrscjwroraacjlbzjskbroajiakjaajwfboqjjofwxsajuadboxdojdyljejwbkuryyjwjoafrscjwajiakjaajwlujsjourondoralsdlrardoroacjzjllbnj
Mu: 23, Sh: 6, M: hfsqysxogkxktguaumxxsrjimxjluoablsfauxmjumskugzsokyusajauxmjkuyzujajyjamxoablsfaxajjlsukisbtkaxjsrjtsjjsfokxzssxofgbjsdjmkxgmxsmhusnsfktdahhsfsxjoablsfjsrjtsjjsfudsbsxdaxwmxajubmuajamxaxjlsisuukws
Mu: 23, Sh: 7, M: qobzhbgxptgtcpdjdvggbasrvgsudxjkubojdgvsdvbtdpibxthdbjsjdgvstdhidsjshsjvgxjkubojgjssubdtrbkctjgsbascbssboxtgibbgxopksbmsvtgpvgbvqdbwbotcmjqqbobgsxjkubosbascbssbodmbkbgmjgfvgjsdkvdjsjvgjgsubrbddtfb
Mu: 23, Sh: 8, M: zxkiqkpgycpclymsmeppkjbaepbdmgstdkxsmpebmekcmyrkgcqmksbsmpebcmqrmbsbqbsepgstdkxspsbbdkmcaktlcspbkjblkbbkxgcprkkpgxytbkvbecpyepkezmkfkxclvszzkxkpbgstdkxbkjblkbbkxmvktkpvspoepsbmtemsbsepspbdkakmmcok
Mu: 23, Sh: 9, M: igtrztyphlyluhvbvnyytskjnykmvpbcmtgbvynkvntlvhatplzvtbkbvynklvzavkbkzkbnypbcmtgbybkkmtvljtculbyktskutkktgplyattypghckteknlyhnytnivtotgluebiitgtykpbcmtgktskutkktgvetctyebyxnybkvcnvbkbnybykmtjtvvlxt
Mu: 23, Sh: 10, M: rpcaichyquhudqekewhhcbtswhtveyklvcpkehwtewcueqjcyuiecktkehwtueijetktitkwhyklvcpkhkttvceuscldukhtcbtdcttcpyuhjcchypqltcntwuhqwhcwrecxcpudnkrrcpchtyklvcptcbtdcttcpenclchnkhgwhktelwektkwhkhtvcsceeugc
Mu: 23, Sh: 11, M: ayljrlqhzdqdmzntnfqqlkcbfqcenhtuelytnqfcnfldnzslhdrnltctnqfcdnrsnctcrctfqhtuelytqtccelndblumdtqclkcmlcclyhdqsllqhyzuclwcfdqzfqlfanlglydmwtaalylqchtuelyclkcmlcclynwlulqwtqpfqtcnufntctfqtqcelblnndpl
Mu: 23, Sh: 12, M: jhusauzqimzmviwcwozzutlkozlnwqcdnuhcwzolwoumwibuqmawuclcwzolmwabwlclalcozqcdnuhczcllnuwmkudvmczlutlvulluhqmzbuuzqhidluflomziozuojwupuhmvfcjjuhuzlqcdnuhlutlvulluhwfuduzfczyozclwdowclcozczlnukuwwmyu
Mu: 23, Sh: 13, M: sqdbjdizrviverflfxiidcutxiuwfzlmwdqlfixufxdvfrkdzvjfdlulfixuvfjkfulujulxizlmwdqliluuwdfvtdmevliudcueduudqzvikddizqrmudouxvirxidxsfdydqveolssdqdiuzlmwdqudcueduudqfodmdiolihxilufmxflulxiliuwdtdffvhd
Mu: 23, Sh: 14, M: bzmksmriaerenaouogrrmldcgrdfoiuvfmzuorgdogmeoatmiesomuduorgdeostodudsdugriuvfmzuruddfmoecmvneurdmldnmddmziertmmrizavdmxdgeragrmgbomhmzenxubbmzmrdiuvfmzdmldnmddmzoxmvmrxurqgrudovgoudugrurdfmcmooeqm
Mu: 23, Sh: 15, M: kivtbvarjnanwjxdxpaavumlpamoxrdeovidxapmxpvnxjcvrnbxvdmdxapmnxbcxmdmbmdpardeovidadmmovxnlvewndamvumwvmmvirnacvvarijemvgmpnajpavpkxvqvinwgdkkvivamrdeovimvumwvmmvixgvevagdazpadmxepxdmdpadamovlvxxnzv
Mu: 23, Sh: 16, M: treckejaswjwfsgmgyjjedvuyjvxgamnxermgjyvgyewgsleawkgemvmgjyvwgklgvmvkvmyjamnxermjmvvxegwuenfwmjvedvfevverawjleejarsnvepvywjsyjeytgezerwfpmtterejvamnxervedvfevvergpenejpmjiyjmvgnygmvmyjmjvxeueggwie
Mu: 23, Sh: 17, M: canltnsjbfsfobpvphssnmedhsegpjvwgnavpshephnfpbunjftpnvevpshefptupevetevhsjvwgnavsveegnpfdnwofvsenmeoneenajfsunnsjabwenyehfsbhsnhcpninafoyvccnansejvwgnaenmeoneenapynwnsyvsrhsvepwhpvevhsvsegndnppfrn
Mu: 23, Sh: 18, M: ljwucwbskoboxkyeyqbbwvnmqbnpysefpwjeybqnyqwoykdwsocyweneybqnoycdynencneqbsefpwjebennpwyomwfxoebnwvnxwnnwjsobdwwbsjkfnwhnqobkqbwqlywrwjoxhellwjwbnsefpwjnwvnxwnnwjyhwfwbhebaqbenyfqyeneqbebnpwmwyyoaw
Mu: 23, Sh: 19, M: usfdlfkbtxkxgthnhzkkfewvzkwyhbnoyfsnhkzwhzfxhtmfbxlhfnwnhkzwxhlmhwnwlwnzkbnoyfsnknwwyfhxvfogxnkwfewgfwwfsbxkmffkbstowfqwzxktzkfzuhfafsxgqnuufsfkwbnoyfswfewgfwwfshqfofkqnkjzknwhozhnwnzknkwyfvfhhxjf
Mu: 23, Sh: 20, M: dbomuotkcgtgpcqwqittonfeitfhqkwxhobwqtifqiogqcvokguqowfwqtifgquvqfwfufwitkwxhobwtwffhoqgeoxpgwtfonfpoffobkgtvootkbcxfozfigtcitoidqojobgpzwddobotfkwxhobfonfpoffobqzoxotzwtsitwfqxiqwfwitwtfhoeoqqgso
Mu: 23, Sh: 21, M: mkxvdxctlpcpylzfzrccxwonrcoqztfgqxkfzcrozrxpzlextpdzxfofzcropzdezofodofrctfgqxkfcfooqxzpnxgypfcoxwoyxooxktpcexxctklgoxiorpclrcxrmzxsxkpyifmmxkxcotfgqxkoxwoyxooxkzixgxcifcbrcfozgrzfofrcfcoqxnxzzpbx
Mu: 23, Sh: 22, M: vtgemglcuylyhuioiallgfxwalxzicopzgtoilaxiagyiungcymigoxoilaxyimnixoxmxoalcopzgtoloxxzgiywgphyolxgfxhgxxgtcylngglctupxgrxaylualgavigbgtyhrovvgtglxcopzgtxgfxhgxxgtirgpglrolkaloxipaioxoalolxzgwgiiykg
Mu: 23, Sh: 23, M: ecpnvpuldhuhqdrxrjuupogfjugirlxyipcxrujgrjphrdwplhvrpxgxrujghrvwrgxgvgxjulxyipcxuxggiprhfpyqhxugpogqpggpclhuwppulcdygpagjhudjupjerpkpchqaxeepcpuglxyipcgpogqpggpcrapypuaxutjuxgryjrxgxjuxugipfprrhtp
Mu: 23, Sh: 24, M: nlyweydumqdqzmagasddyxposdpraughrylgadspasyqamfyuqeaygpgadspqaefapgpepgsdughrylgdgppryaqoyhzqgdpyxpzyppyluqdfyydulmhpyjpsqdmsdysnaytylqzjgnnylydpughrylpyxpzyppylajyhydjgdcsdgpahsagpgsdgdpryoyaaqcy
Mu: 23, Sh: 25, M: wuhfnhmdvzmzivjpjbmmhgyxbmyajdpqahupjmbyjbhzjvohdznjhpypjmbyzjnojypynypbmdpqahupmpyyahjzxhqizpmyhgyihyyhudzmohhmduvqyhsybzmvbmhbwjhchuzispwwhuhmydpqahuyhgyihyyhujshqhmspmlbmpyjqbjpypbmpmyahxhjjzlh
Mu: 25, Sh: 0, M: pjwqowlkmylyzmcucellwtvselvbckuxbwjuclevcewycmrwkyocwuvuclevycorcvuvovuelkuxbwjuluvvbwcyswxzyulvwtvzwvvwjkylrwwlkjmxvwdveylmelwepcwhwjyzduppwjwlvkuxbwjvwtvzwvvwjcdwxwldulieluvcxecuvuelulvbwswccyiw
Mu: 25, Sh: 1, M: qkxrpxmlnzmzandvdfmmxuwtfmwcdlvycxkvdmfwdfxzdnsxlzpdxvwvdmfwzdpsdwvwpwvfmlvycxkvmvwwcxdztxyazvmwxuwaxwwxklzmsxxmlknywxewfzmnfmxfqdxixkzaevqqxkxmwlvycxkwxuwaxwwxkdexyxmevmjfmvwdyfdvwvfmvmwcxtxddzjx
Mu: 25, Sh: 2, M: rlysqynmoanaboewegnnyvxugnxdemwzdylwengxegyaeotymaqeywxwengxaeqtexwxqxwgnmwzdylwnwxxdyeauyzbawnxyvxbyxxylmantyynmlozxyfxganognygreyjylabfwrrylynxmwzdylxyvxbyxxylefyzynfwnkgnwxezgewxwgnwnxdyuyeeaky
Mu: 25, Sh: 3, M: smztrzonpbobcpfxfhoozwyvhoyefnxaezmxfohyfhzbfpuznbrfzxyxfohybfrufyxyryxhonxaezmxoxyyezfbvzacbxoyzwyczyyzmnbouzzonmpayzgyhbophozhsfzkzmbcgxsszmzoynxaezmyzwyczyyzmfgzazogxolhoxyfahfxyxhoxoyezvzffblz
Mu: 25, Sh: 4, M: tnausapoqcpcdqgygippaxzwipzfgoybfanygpizgiacgqvaocsgayzygpizcgsvgzyzszyipoybfanypyzzfagcwabdcypzaxzdazzanocpvaaponqbzahzicpqipaitgalancdhyttanapzoybfanzaxzdazzanghabaphypmipyzgbigyzyipypzfawaggcma
Mu: 25, Sh: 5, M: uobvtbqprdqderhzhjqqbyaxjqaghpzcgbozhqjahjbdhrwbpdthbzazhqjadhtwhazatazjqpzcgbozqzaagbhdxbcedzqabyaebaabopdqwbbqporcabiajdqrjqbjuhbmbodeizuubobqapzcgboabyaebaabohibcbqizqnjqzahcjhzazjqzqagbxbhhdnb
Mu: 25, Sh: 6, M: vpcwucrqserefsiaikrrczbykrbhiqadhcpairkbikceisxcqeuicabairkbeiuxibabubakrqadhcparabbhcieycdfearbczbfcbbcpqerxccrqpsdbcjbkerskrckvicncpefjavvcpcrbqadhcpbczbfcbbcpijcdcrjarokrabidkiabakrarbhcyciieoc
Mu: 25, Sh: 7, M: wqdxvdsrtfsfgtjbjlssdaczlscijrbeidqbjslcjldfjtydrfvjdbcbjslcfjvyjcbcvcblsrbeidqbsbccidjfzdegfbscdacgdccdqrfsyddsrqtecdkclfstlsdlwjdodqfgkbwwdqdscrbeidqcdacgdccdqjkdedskbsplsbcjeljbcblsbscidzdjjfpd
Mu: 25, Sh: 8, M: xreywetsugtghukckmttebdamtdjkscfjercktmdkmegkuzesgwkecdcktmdgkwzkdcdwdcmtscfjerctcddjekgaefhgctdebdheddersgtzeetsrufdeldmgtumtemxkeperghlcxxeretdscfjerdebdhedderklefetlctqmtcdkfmkcdcmtctdjeaekkgqe
Mu: 25, Sh: 9, M: ysfzxfutvhuhivldlnuufcebnuekltdgkfsdlunelnfhlvafthxlfdedlunehlxaledexednutdgkfsdudeekflhbfgihduefceifeefsthuaffutsvgefmenhuvnufnylfqfshimdyyfsfuetdgkfsefceifeefslmfgfumdurnudelgnldednuduekfbfllhrf
Mu: 25, Sh: 10, M: ztgaygvuwivijwmemovvgdfcovflmuehlgtemvofmogimwbguiymgefemvofimybmfefyfeovuehlgtevefflgmicghjievfgdfjgffgtuivbggvutwhfgnfoivwovgozmgrgtijnezzgtgvfuehlgtfgdfjgffgtmnghgvnevsovefmhomefeovevflgcgmmisg
Mu: 25, Sh: 11, M: auhbzhwvxjwjkxnfnpwwhegdpwgmnvfimhufnwpgnphjnxchvjznhfgfnwpgjnzcngfgzgfpwvfimhufwfggmhnjdhikjfwghegkhgghuvjwchhwvuxighogpjwxpwhpanhshujkofaahuhwgvfimhughegkhgghunohihwofwtpwfgnipnfgfpwfwgmhdhnnjth
Mu: 25, Sh: 12, M: bvicaixwykxklyogoqxxifheqxhnowgjnivgoxqhoqikoydiwkaoighgoxqhkoadohghahgqxwgjnivgxghhniokeijlkgxhifhlihhivwkxdiixwvyjhiphqkxyqxiqboitivklpgbbivixhwgjnivhifhlihhivopijixpgxuqxghojqoghgqxgxhnieiookui
Mu: 25, Sh: 13, M: cwjdbjyxzlylmzphpryyjgifryiopxhkojwhpyriprjlpzejxlbpjhihpyrilpbepihibihryxhkojwhyhiiojplfjkmlhyijgimjiijwxlyejjyxwzkijqirlyzryjrcpjujwlmqhccjwjyixhkojwijgimjiijwpqjkjyqhyvryhipkrphihryhyiojfjpplvj
Mu: 25, Sh: 14, M: dxkeckzyamzmnaqiqszzkhjgszjpqyilpkxiqzsjqskmqafkymcqkijiqzsjmqcfqjijcjiszyilpkxizijjpkqmgklnmizjkhjnkjjkxymzfkkzyxaljkrjsmzaszksdqkvkxmnriddkxkzjyilpkxjkhjnkjjkxqrklkzrizwszijqlsqijiszizjpkgkqqmwk
Mu: 25, Sh: 15, M: eylfdlazbnanobrjrtaalikhtakqrzjmqlyjratkrtlnrbglzndrljkjratknrdgrkjkdkjtazjmqlyjajkkqlrnhlmonjaklikolkklyznagllazybmklsktnabtalterlwlynosjeelylakzjmqlyklikolkklyrslmlasjaxtajkrmtrjkjtajakqlhlrrnxl
Mu: 25, Sh: 16, M: fzmgembacobopcsksubbmjliublrsaknrmzksbulsumoschmaoesmklksbulosehslklelkubaknrmzkbkllrmsoimnpokblmjlpmllmzaobhmmbazcnlmtluobcubmufsmxmzoptkffmzmblaknrmzlmjlpmllmzstmnmbtkbyubklsnusklkubkblrmimssoym
Mu: 25, Sh: 17, M: ganhfncbdpcpqdtltvccnkmjvcmstblosnaltcvmtvnptdinbpftnlmltcvmptfitmlmfmlvcblosnalclmmsntpjnoqplcmnkmqnmmnabpcinncbadomnumvpcdvcnvgtnynapqulggnancmblosnamnkmqnmmnatunonculczvclmtovtlmlvclcmsnjnttpzn
Mu: 25, Sh: 18, M: hboigodceqdqreumuwddolnkwdntucmptobmudwnuwoquejocqguomnmudwnqugjunmngnmwdcmptobmdmnntouqkoprqmdnolnronnobcqdjoodcbepnovnwqdewdowhuozobqrvmhhobodncmptobnolnronnobuvopodvmdawdmnupwumnmwdmdntokouuqao
Mu: 25, Sh: 19, M: icpjhpedfrersfvnvxeepmolxeouvdnqupcnvexovxprvfkpdrhvpnonvexorvhkvonohonxednqupcnenooupvrlpqsrneopmospoopcdrekppedcfqopwoxrefxepxivpapcrswniipcpeodnqupcopmospoopcvwpqpewnebxenovqxvnonxeneouplpvvrbp
Mu: 25, Sh: 20, M: jdqkiqfegsfstgwowyffqnpmyfpvweorvqdowfypwyqswglqesiwqopowfypswilwpopipoyfeorvqdofoppvqwsmqrtsofpqnptqppqdesflqqfedgrpqxpysfgyfqyjwqbqdstxojjqdqfpeorvqdpqnptqppqdwxqrqfxofcyfopwrywopoyfofpvqmqwwscq
Mu: 25, Sh: 21, M: kerljrgfhtgtuhxpxzggroqnzgqwxfpswrepxgzqxzrtxhmrftjxrpqpxgzqtxjmxqpqjqpzgfpswrepgpqqwrxtnrsutpgqroqurqqreftgmrrgfehsqryqztghzgrzkxrcretuypkkrergqfpswreqroqurqqrexyrsrgypgdzgpqxszxpqpzgpgqwrnrxxtdr
Mu: 25, Sh: 22, M: lfsmkshgiuhuviyqyahhsproahrxygqtxsfqyharyasuyinsgukysqrqyharuyknyrqrkrqahgqtxsfqhqrrxsyuostvuqhrsprvsrrsfguhnsshgfitrszrauhiahsalysdsfuvzqllsfshrgqtxsfrsprvsrrsfyzstshzqheahqrytayqrqahqhrxsosyyues
Mu: 25, Sh: 23, M: mgtnltihjvivwjzrzbiitqspbisyzhruytgrzibszbtvzjothvlztrsrzibsvzlozsrslsrbihruytgrirssytzvptuwvristqswtsstghviottihgjustasbvijbitbmztetgvwarmmtgtishruytgstqswtsstgzatutiarifbirszubzrsrbirisytptzzvft
Mu: 25, Sh: 24, M: nhuomujikwjwxkasacjjurtqcjtzaisvzuhsajctacuwakpuiwmaustsajctwampatstmtscjisvzuhsjsttzuawquvxwsjturtxuttuhiwjpuujihkvtubtcwjkcjucnaufuhwxbsnnuhujtisvzuhturtxuttuhabuvujbsjgcjstavcastscjsjtzuquaawgu
Mu: 25, Sh: 25, M: oivpnvkjlxkxylbtbdkkvsurdkuabjtwavitbkdubdvxblqvjxnbvtutbkduxbnqbutunutdkjtwavitktuuavbxrvwyxtkuvsuyvuuvijxkqvvkjilwuvcudxkldkvdobvgvixyctoovivkujtwaviuvsuyvuuvibcvwvkctkhdktubwdbtutdktkuavrvbbxhv
--- 0.0154259204865 seconds ---

for input of given cipher text.
'''