'''
Author: Walker Kroubalkian
Implementation of Shift Cipher Decryption without Key in Python 2.7
'''

import time

cipherText = "WIVHLVETPRERCPJZJTRESVLJVUFEFKYVIKPGVJFWTZGYVIJKFFSLKZKZJEFKLJLRCCPRJJZDGCVRJZKZJNZKYJYZWKTZGYVIJDREPFWKYVJVFKYVITZGYVIJNZCCRGGVRIYVIVZEKYVEVOKWVNDFEKY"

def shiftDecrypt(c,k):
    c = c.lower()
    s = ""
    v = ord("a")
    for x in c:
        s+=chr(v+(ord(x)-k-v)%26)
    return s

def shiftBruteForce(c):
    for i in range(1,26):
        print "K: " + str(i) + ", M: " + shiftDecrypt(c, i)
    exit

start = time.time()
shiftBruteForce(cipherText)
print ("--- %s seconds ---" % (time.time()-start))

'''
Prints

K: 1, M: vhugkudsoqdqboiyisqdrukiutedejxuhjofuievsyfxuhijeerkjyjyidejkikqbboqiiycfbuqiyjyimyjxixyvjsyfxuhicqdoevjxuiuejxuhsyfxuhimybbqffuqhxuhuydjxudunjvumcedjx
K: 2, M: ugtfjtcrnpcpanhxhrpcqtjhtsdcdiwtginethdurxewtghiddqjixixhcdijhjpaanphhxbeatphxixhlxiwhwxuirxewtghbpcnduiwthtdiwtgrxewtghlxaapeetpgwtgtxciwtctmiutlbdciw
K: 3, M: tfseisbqmobozmgwgqobpsigsrcbchvsfhmdsgctqwdvsfghccpihwhwgbchigiozzmoggwadzsogwhwgkwhvgvwthqwdvsfgaobmcthvsgschvsfqwdvsfgkwzzoddsofvsfswbhvsbslhtskacbhv
K: 4, M: serdhraplnanylfvfpnaorhfrqbabgureglcrfbspvcurefgbbohgvgvfabghfhnyylnffvzcyrnfvgvfjvgufuvsgpvcurefznalbsgurfrbgurepvcurefjvyynccrneurervagurarkgsrjzbagu
K: 5, M: rdqcgqzokmzmxkeueomznqgeqpazaftqdfkbqearoubtqdefaangfufuezafgegmxxkmeeuybxqmeufueiufteturfoubtqdeymzkarftqeqaftqdoubtqdeiuxxmbbqmdtqdquzftqzqjfrqiyazft
K: 6, M: qcpbfpynjlylwjdtdnlympfdpozyzespcejapdzqntaspcdezzmfetetdyzefdflwwjlddtxawpldtetdhtesdstqentaspcdxlyjzqespdpzespcntaspcdhtwwlaaplcspcptyespypieqphxzyes
K: 7, M: pboaeoxmikxkvicscmkxloeconyxydrobdizocypmszrobcdyyledsdscxydecekvvikccswzvokcsdscgsdrcrspdmszrobcwkxiypdrocoydrobmszrobcgsvvkzzokbrobosxdroxohdpogwyxdr
K: 8, M: oanzdnwlhjwjuhbrbljwkndbnmxwxcqnachynbxolryqnabcxxkdcrcrbwxcdbdjuuhjbbrvyunjbrcrbfrcqbqroclryqnabvjwhxocqnbnxcqnalryqnabfruujyynjaqnanrwcqnwngconfvxwcq
K: 9, M: nzmycmvkgivitgaqakivjmcamlwvwbpmzbgxmawnkqxpmzabwwjcbqbqavwbcacittgiaaquxtmiaqbqaeqbpapqnbkqxpmzauivgwnbpmamwbpmzkqxpmzaeqttixxmizpmzmqvbpmvmfbnmeuwvbp
K: 10, M: mylxblujfhuhsfzpzjhuilbzlkvuvaolyafwlzvmjpwolyzavvibapapzuvabzbhssfhzzptwslhzpapzdpaozopmajpwolyzthufvmaolzlvaolyjpwolyzdpsshwwlhyolylpuaoluleamldtvuao
K: 11, M: lxkwaktiegtgreyoyigthkaykjutuznkxzevkyuliovnkxyzuuhazozoytuzayagrregyyosvrkgyozoycoznynolziovnkxysgteulznkykuznkxiovnkxycorrgvvkgxnkxkotznktkdzlkcsutzn
K: 12, M: kwjvzjshdfsfqdxnxhfsgjzxjitstymjwydujxtkhnumjwxyttgzynynxstyzxzfqqdfxxnruqjfxnynxbnymxmnkyhnumjwxrfsdtkymjxjtymjwhnumjwxbnqqfuujfwmjwjnsymjsjcykjbrtsym
K: 13, M: jviuyirgcerepcwmwgerfiywihsrsxlivxctiwsjgmtlivwxssfyxmxmwrsxywyeppcewwmqtpiewmxmwamxlwlmjxgmtlivwqercsjxliwisxlivgmtlivwamppettievlivimrxliribxjiaqsrxl
K: 14, M: iuhtxhqfbdqdobvlvfdqehxvhgrqrwkhuwbshvriflskhuvwrrexwlwlvqrwxvxdoobdvvlpsohdvlwlvzlwkvkliwflskhuvpdqbriwkhvhrwkhuflskhuvzloodsshdukhuhlqwkhqhawihzprqwk
K: 15, M: htgswgpeacpcnaukuecpdgwugfqpqvjgtvarguqhekrjgtuvqqdwvkvkupqvwuwcnnacuukorngcukvkuykvjujkhvekrjgtuocpaqhvjgugqvjgtekrjgtuyknncrrgctjgtgkpvjgpgzvhgyoqpvj
K: 16, M: gsfrvfodzbobmztjtdbocfvtfepopuifsuzqftpgdjqifstuppcvujujtopuvtvbmmzbttjnqmfbtjujtxjuitijgudjqifstnbozpguiftfpuifsdjqifstxjmmbqqfbsifsfjouifofyugfxnpoui
K: 17, M: frequencyanalysiscanbeusedonothertypesofcipherstoobutitisnotusuallyassimpleasitiswithshiftciphersmanyoftheseothercipherswillappearhereinthenextfewmonth
K: 18, M: eqdptdmbxzmzkxrhrbzmadtrdcnmnsgdqsxodrnebhogdqrsnnatshshrmnstrtzkkxzrrhlokdzrhshrvhsgrghesbhogdqrlzmxnesgdrdnsgdqbhogdqrvhkkzoodzqgdqdhmsgdmdwsedvlnmsg
K: 19, M: dpcosclawylyjwqgqaylzcsqcbmlmrfcprwncqmdagnfcpqrmmzsrgrgqlmrsqsyjjwyqqgknjcyqgrgqugrfqfgdragnfcpqkylwmdrfcqcmrfcpagnfcpqugjjynncypfcpcglrfclcvrdcukmlrf
K: 20, M: cobnrbkzvxkxivpfpzxkybrpbalklqeboqvmbplczfmebopqllyrqfqfpklqrprxiivxppfjmibxpfqfptfqepefcqzfmebopjxkvlcqebpblqebozfmeboptfiixmmbxoebobfkqebkbuqcbtjlkqe
K: 21, M: bnamqajyuwjwhuoeoywjxaqoazkjkpdanpulaokbyeldanopkkxqpepeojkpqoqwhhuwooeilhawoepeosepdodebpyeldanoiwjukbpdaoakpdanyeldanosehhwllawndanaejpdajatpbasikjpd
K: 22, M: amzlpzixtvivgtndnxviwzpnzyjijoczmotkznjaxdkczmnojjwpododnijopnpvggtvnndhkgzvndodnrdocncdaoxdkczmnhvitjaocznzjoczmxdkczmnrdggvkkzvmczmzdioczizsoazrhjioc
K: 23, M: zlykoyhwsuhufsmcmwuhvyomyxihinbylnsjymizwcjbylmniivoncncmhinomouffsummcgjfyumcncmqcnbmbcznwcjbylmguhsiznbymyinbylwcjbylmqcffujjyulbylychnbyhyrnzyqgihnb
K: 24, M: ykxjnxgvrtgterlblvtguxnlxwhghmaxkmrixlhyvbiaxklmhhunmbmblghmnlnteertllbfiextlbmblpbmalabymvbiaxklftgrhymaxlxhmaxkvbiaxklpbeetiixtkaxkxbgmaxgxqmyxpfhgma
K: 25, M: xjwimwfuqsfsdqkakusftwmkwvgfglzwjlqhwkgxuahzwjklggtmlalakfglmkmsddqskkaehdwskalakoalzkzaxluahzwjkesfqgxlzwkwglzwjuahzwjkoaddshhwsjzwjwaflzwfwplxwoegflz
None
--- 0.00116586685181 seconds ---

for input of given cipher text.
'''